'use strict';
/* LogiQ – task generators, part 2: combinatorics, numbers, space, olympiad, interactive puzzles. */

const DAYS = [S('pondelok', 'Monday'), S('utorok', 'Tuesday'), S('streda', 'Wednesday'), S('štvrtok', 'Thursday'), S('piatok', 'Friday'), S('sobota', 'Saturday'), S('nedeľa', 'Sunday')];
const DAYS_ACC = ['pondelok', 'utorok', 'stredu', 'štvrtok', 'piatok', 'sobotu', 'nedeľu'];
const num = (key, extra) => Object.assign({ type: 'number' }, extra);

/* ---------- combinatorics ---------- */
reg('perm', 'combi', 2, c => {
  const { D, k, r } = c, v = k % 5, j = Math.floor(k / 5), n = clamp(lerp(3, 6, D) + j, 3, 8), P = names(r, 2);
  if (v === 0) return { title: S('Rad detí', 'Children in a row'), type: 'number', prompt: S(`Skupina ${n} detí sa chce postaviť do radu na fotku. Koľkými rôznymi spôsobmi sa môžu zoradiť?`, `A group of ${n} children wants to line up for a photo. In how many different orders can they stand?`), data: { answer: fact(n) },
    hints: [S('Koľko možností je na prvé miesto? A na druhé, keď je prvé obsadené?', 'How many options are there for the first place? And for the second once the first is taken?'), S('Počet možností postupne klesá o 1. Vynásob ich.', 'The number of options drops by 1 each time. Multiply them.')],
    explain: [S(`Na prvé miesto je ${n} možností, na druhé ${n - 1}, na tretie ${n - 2} … až po 1.`, `There are ${n} options for the first place, ${n - 1} for the second, ${n - 2} for the third … down to 1.`), S(`Súčin ${range(n).map(i => n - i).join(' · ')} = ${fact(n)}.`, `The product ${range(n).map(i => n - i).join(' · ')} = ${fact(n)}.`)] };
  if (v === 1) return { title: S('Stupne víťazov', 'The podium'), type: 'number', prompt: S(`Na štarte je skupina ${n + 2} bežcov. Koľko rôznych možností je na obsadenie zlatej, striebornej a bronzovej priečky?`, `A group of ${n + 2} runners is on the start line. How many different ways can the gold, silver and bronze places be filled?`), data: { answer: (n + 2) * (n + 1) * n },
    hints: [S('Koľko bežcov môže získať zlato? Koľko potom striebro?', 'How many runners can win gold? How many can then win silver?'), S('Medaily sú rôzne, takže na poradí záleží.', 'The medals differ, so order matters.')],
    explain: [S(`Zlato: ${n + 2} možností, striebro: ${n + 1}, bronz: ${n}.`, `Gold: ${n + 2} options, silver: ${n + 1}, bronze: ${n}.`), S(`Spolu ${n + 2} · ${n + 1} · ${n} = ${(n + 2) * (n + 1) * n}.`, `In total ${n + 2} · ${n + 1} · ${n} = ${(n + 2) * (n + 1) * n}.`)] };
  if (v === 2) return { title: S('Kamaráti vedľa seba', 'Friends side by side'), type: 'number', prompt: S(`Skupina ${n} detí sa stavia do radu. ${P[0]} a ${P[1]} chcú stáť vedľa seba (v ľubovoľnom poradí). Koľko je takých usporiadaní?`, `A group of ${n} children lines up. ${P[0]} and ${P[1]} want to stand next to each other (in either order). How many such arrangements are there?`), data: { answer: 2 * fact(n - 1) },
    hints: [S('Spoj dvoch kamarátov do jednej „dvojice“. Koľko miest v rade potom usporadúvaš?', 'Glue the two friends into one “pair”. How many items are you then arranging?'), S('A v dvojici môžu stáť dvoma spôsobmi.', 'And inside the pair they can stand in two ways.')],
    explain: [S(`Dvojicu berieme ako jeden celok: usporadúvame ${n - 1} celkov, čo je ${fact(n - 1)} spôsobov.`, `Treat the pair as one block: we arrange ${n - 1} blocks, which is ${fact(n - 1)} ways.`), S(`V dvojici sú 2 poradia, preto 2 · ${fact(n - 1)} = ${2 * fact(n - 1)}.`, `Inside the pair there are 2 orders, so 2 · ${fact(n - 1)} = ${2 * fact(n - 1)}.`)] };
  if (v === 3) return { title: S('Okrúhly stôl', 'The round table'), type: 'number', prompt: S(`Skupina ${n} detí sa posadí okolo okrúhleho stola. Dve rozsadenia, ktoré sa líšia iba otočením celého stola, považujeme za rovnaké. Koľko rôznych rozsadení existuje?`, `A group of ${n} children sits around a round table. Two seatings that differ only by rotating the whole table count as the same. How many different seatings are there?`), data: { answer: fact(n - 1) },
    hints: [S('Posaď jedno dieťa na pevné miesto. Čo ostane usporiadať?', 'Seat one child in a fixed place. What is left to arrange?'), S('Zvyšných detí je o jedno menej.', 'There is one child fewer left.')],
    explain: [S('Jedno dieťa pevne posadíme – tým „zamedzíme“ otáčaniu stola.', 'Fix one child – that removes the rotation.'), S(`Ostatných ${n - 1} usporiadame do radu okolo neho: ${n - 1}! = ${fact(n - 1)}.`, `Arrange the other ${n - 1} around: ${n - 1}! = ${fact(n - 1)}.`)] };
  const m = clamp(lerp(4, 7, D) + (j % 2), 4, 8), digs = range(m).map(i => i + 1); let ans = 0; digs.forEach(a => digs.forEach(b => digs.forEach(cc => { if (a !== b && b !== cc && a !== cc) ans++; })));
  return { title: S('Trojciferné čísla', 'Three-digit numbers'), type: 'number', prompt: S(`Z číslic ${digs.join(', ')} vytvárame trojciferné čísla, v ktorých sa žiadna číslica neopakuje. Koľko takých čísel vznikne?`, `From the digits ${digs.join(', ')} we build three-digit numbers with no repeated digit. How many such numbers are there?`), data: { answer: ans },
    hints: [S('Koľko číslic môžeš dať na miesto stoviek? A koľko zostane na desiatky?', 'How many digits can go in the hundreds place? And how many remain for the tens?'), S('Každou použitou číslicou sa výber zmenší o 1.', 'Each used digit reduces the choice by 1.')],
    explain: [S(`Stovky: ${m} možností, desiatky: ${m - 1}, jednotky: ${m - 2}.`, `Hundreds: ${m} options, tens: ${m - 1}, units: ${m - 2}.`), S(`Spolu ${m} · ${m - 1} · ${m - 2} = ${ans}.`, `In total ${m} · ${m - 1} · ${m - 2} = ${ans}.`)] };
});

reg('choose', 'combi', 2, c => {
  const { D, k } = c, v = k % 5, j = Math.floor(k / 5), n = clamp(lerp(5, 11, D) + j, 5, 16);
  if (v === 0) return { title: S('Delegácia', 'The delegation'), type: 'number', prompt: S(`Zo skupiny ${n} detí vyberáme dvojčlennú delegáciu. Koľkými spôsobmi to môžeme urobiť?`, `We choose a two-person delegation from a group of ${n} children. In how many ways can it be done?`), data: { answer: binom(n, 2) },
    hints: [S('Najprv spočítaj usporiadané dvojice – koľko ich je?', 'First count ordered pairs – how many are there?'), S('Každú dvojicu si započítal dvakrát. Čo s tým?', 'You counted every pair twice. What to do about it?')],
    explain: [S(`Usporiadaných dvojíc je ${n} · ${n - 1} = ${n * (n - 1)}.`, `There are ${n} · ${n - 1} = ${n * (n - 1)} ordered pairs.`), S(`Na poradí nezáleží, preto delíme dvoma: ${n * (n - 1) / 2}.`, `Order does not matter, so divide by 2: ${n * (n - 1) / 2}.`)] };
  if (v === 1) return { title: S('Trojčlenný tím', 'A team of three'), type: 'number', prompt: S(`Zo skupiny ${n} detí vyberáme trojčlenný tím. Koľko rôznych tímov môže vzniknúť?`, `We choose a team of three from a group of ${n} children. How many different teams are possible?`), data: { answer: binom(n, 3) },
    hints: [S('Koľko je usporiadaných trojíc?', 'How many ordered triples are there?'), S('Každý tím sa v nich objaví 3! = 6-krát.', 'Each team appears 3! = 6 times among them.')],
    explain: [S(`Usporiadaných trojíc: ${n} · ${n - 1} · ${n - 2} = ${n * (n - 1) * (n - 2)}.`, `Ordered triples: ${n} · ${n - 1} · ${n - 2} = ${n * (n - 1) * (n - 2)}.`), S(`Každý tím je započítaný 6-krát, takže ${n * (n - 1) * (n - 2)} : 6 = ${binom(n, 3)}.`, `Each team is counted 6 times, so ${n * (n - 1) * (n - 2)} : 6 = ${binom(n, 3)}.`)] };
  if (v === 2) return { title: S('Podávanie rúk', 'Handshakes'), type: 'number', prompt: S(`Na stretnutí je skupina ${n} ľudí. Každý si podá ruku s každým iným práve raz. Koľko podaní rúk bude?`, `A group of ${n} people meets. Everybody shakes hands with everybody else exactly once. How many handshakes are there?`), data: { answer: binom(n, 2) },
    hints: [S('Koľkým ľuďom podá ruku jeden človek?', 'How many people does one person shake hands with?'), S('Každé podanie rúk si započítal dvakrát (z oboch strán).', 'You counted each handshake twice (from both sides).')],
    explain: [S(`Každý podá ruku ${n - 1} ľuďom, spolu ${n} · ${n - 1} = ${n * (n - 1)}.`, `Everybody shakes ${n - 1} hands, in total ${n} · ${n - 1} = ${n * (n - 1)}.`), S(`Každé podanie sme počítali dvakrát, preto ${n * (n - 1)} : 2 = ${binom(n, 2)}.`, `Each handshake was counted twice, so ${n * (n - 1)} : 2 = ${binom(n, 2)}.`)] };
  if (v === 3) { const m = n + 1; return { title: S('Uhlopriečky', 'Diagonals'), type: 'number', prompt: S(`Pravidelný ${m}-uholník má ${m} vrcholov. Koľko uhlopriečok možno v ňom nakresliť?`, `A regular polygon with ${m} vertices. How many diagonals can be drawn in it?`), data: { answer: m * (m - 3) / 2 },
    hints: [S('Z jedného vrcholu: do koľkých vrcholov vedie uhlopriečka? (Nie do seba a nie do susedov.)', 'From one vertex: to how many vertices can a diagonal go? (Not to itself or its neighbours.)'), S('Každú uhlopriečku si započítal dvakrát.', 'You counted each diagonal twice.')],
    explain: [S(`Z každého vrcholu vedie ${m - 3} uhlopriečok.`, `From every vertex ${m - 3} diagonals start.`), S(`Spolu ${m} · ${m - 3} : 2 = ${m * (m - 3) / 2} (každá je započítaná dvakrát).`, `In total ${m} · ${m - 3} : 2 = ${m * (m - 3) / 2} (each is counted twice).`)] }; }
  const t = clamp(n - 2, 3, 12);
  return { title: S('Pizza s prísadami', 'Pizza toppings'), type: 'number', prompt: S(`V pizzerii majú ${t} druhov prísad. Pizza môže mať ľubovoľnú kombináciu prísad (každú buď dáme, alebo nie; aj pizza bez prísad je povolená). Koľko rôznych pízz možno objednať?`, `A pizzeria has ${t} toppings. A pizza can have any combination (each topping is either on or off; a plain pizza is allowed). How many different pizzas can be ordered?`), data: { answer: 2 ** t },
    hints: [S('Pri jednej prísade sú dve možnosti. Čo pri dvoch prísadách?', 'With one topping there are two options. What with two toppings?'), S('Každá ďalšia prísada počet zdvojnásobí.', 'Every extra topping doubles the count.')],
    explain: [S('Pri každej prísade sú 2 možnosti (áno/nie) a rozhodnutia sú nezávislé.', 'Each topping has 2 options (yes/no) and the decisions are independent.'), S(`Preto 2 · 2 · … (${t}-krát) = 2^${t} = ${2 ** t}.`, `So 2 · 2 · … (${t} times) = 2^${t} = ${2 ** t}.`)] };
});

const RULES = [
  { f: ds => ds.every(d => d % 2 === 1), t: S('všetky cifry sú nepárne', 'all digits are odd') }, { f: ds => ds.every(d => d % 2 === 0), t: S('všetky cifry sú párne', 'all digits are even') },
  { f: ds => !ds.includes(0) && !ds.includes(5), t: S('číslo neobsahuje cifru 0 ani 5', 'the number contains neither digit 0 nor 5') }, { f: ds => new Set(ds).size === 3, t: S('všetky tri cifry sú rôzne', 'all three digits are different') },
  { f: ds => ds[0] < ds[1] && ds[1] < ds[2], t: S('cifry idú prísne rastúco (zľava doprava)', 'the digits strictly increase (left to right)') }, { f: ds => ds[0] + ds[1] + ds[2] === 10, t: S('ciferný súčet je 10', 'the digit sum is 10') },
  { f: ds => ds[0] === ds[2], t: S('je to „zrkadlové“ číslo (číta sa rovnako odpredu aj odzadu)', 'it is a palindrome (reads the same both ways)') }, { f: ds => ds.includes(7), t: S('číslo obsahuje aspoň jednu cifru 7', 'the number contains at least one digit 7') },
  { f: ds => ds[0] + ds[1] + ds[2] === 9, t: S('ciferný súčet je 9', 'the digit sum is 9') }, { f: ds => ds[0] * ds[1] * ds[2] === 0, t: S('aspoň jedna cifra je 0', 'at least one digit is 0') }
];
reg('product', 'combi', 2, c => {
  const { D, k, r, g } = c, vs = g >= 4 ? [0, 1, 2, 3] : [0, 2], v = vs[k % vs.length], j = Math.floor(k / vs.length);
  if (v === 0) { const a = ri(r, 2, lerp(4, 9, D)) + j % 3, b = ri(r, 2, lerp(3, 7, D)) + (j + 1) % 3, cc = ri(r, 2, 4); return { title: S('Oblečenie', 'Outfits'), type: 'number', visual: () => kpm([kspan('👕', a), kop('·'), kspan('👖', b), kop('·'), kspan('🧢', cc)]), prompt: S(`Koľko rôznych oblečení vieš zostaviť?`, `How many different outfits can you make? (1 👕 + 1 👖 + 1 🧢)`), data: { answer: a * b * cc },
    hints: [S('Vyber si tričko. S koľkými kombináciami nohavíc a čiapok sa dá nosiť?', 'Pick a T-shirt. With how many trouser-and-hat combinations can it be worn?'), S('Vynásob počty možností pri každom výbere.', 'Multiply the number of options at each choice.')], explain: [S(`Pre každé tričko je ${b} · ${cc} = ${b * cc} kombinácií.`, `For every T-shirt there are ${b} · ${cc} = ${b * cc} combinations.`), S(`Spolu ${a} · ${b} · ${cc} = ${a * b * cc}.`, `In total ${a} · ${b} · ${cc} = ${a * b * cc}.`)] }; }
  if (v === 1) { const d = clamp(2 + Math.floor(D * 3) + ri(r, 0, 2), 2, 6), sets = ri(r, 2, 3); const kinds = Math.pow(10, d); return { title: S('Číselný zámok', 'Number lock'), type: 'number', prompt: S(`🔒 Zámok má ${cnt(d, 'dial', 'sk')} s číslami 0–9. Koľko kódov sa dá nastaviť?`, `🔒 A lock has ${d} dials with digits 0–9. How many codes can be set?`), data: { answer: kinds },
    hints: [S('Koľko možností má jeden kotúčik?', 'How many options does one dial have?'), S('Kotúčiky sú nezávislé – možnosti sa násobia.', 'The dials are independent – the options multiply.')], explain: [S('Každý kotúčik má 10 možností.', 'Each dial has 10 options.'), S(`Spolu 10^${d} = ${kinds}.`, `In total 10^${d} = ${kinds}.`)] }; }
  if (v === 2) { const p = ri(r, 2, lerp(3, 7, D)) + j % 3, q = ri(r, 2, lerp(3, 6, D)) + (j + 2) % 3, s2 = ri(r, 2, 5); return { title: S('Cesty medzi mestami', 'Roads between towns'), type: 'number', prompt: S(`Z mesta A do B vedie ${p} ciest, z B do C ${q} ciest a z C do D ${s2} ciest. Koľko rôznych trás vedie z A do D cez B a C?`, `There are ${p} roads from A to B, ${q} from B to C and ${s2} from C to D. How many different routes lead from A to D via B and C?`), data: { answer: p * q * s2 },
    hints: [S('Koľkými spôsobmi sa dostaneš z A do B? A potom ďalej do C?', 'In how many ways can you get from A to B? And then on to C?'), S('Počty ciest na jednotlivých úsekoch sa násobia.', 'The numbers of roads on the legs multiply.')], explain: [S(`Úsek A–B: ${p}, B–C: ${q}, C–D: ${s2}.`, `Leg A–B: ${p}, B–C: ${q}, C–D: ${s2}.`), S(`Trás je ${p} · ${q} · ${s2} = ${p * q * s2}.`, `There are ${p} · ${q} · ${s2} = ${p * q * s2} routes.`)] }; }
  const rule = RULES[(j * 3 + k + ri(r, 0, 1)) % RULES.length]; let ans = 0; for (let x = 100; x <= 999; x++) if (rule.f(String(x).split('').map(Number))) ans++;
  return { title: S('Trojciferné čísla s pravidlom', 'Three-digit numbers with a rule'), type: 'number', prompt: both(l => l === 'sk' ? `Koľko trojciferných čísel (od 100 do 999) spĺňa podmienku: ${rule.t.sk}?` : `How many three-digit numbers (100 to 999) satisfy: ${rule.t.en}?`), data: { answer: ans },
    hints: [S('Rozdeľ číslo na cifry: stovky, desiatky, jednotky. Koľko možností má každá?', 'Split the number into hundreds, tens, units. How many options does each have?'), S('Pozor na to, že stovky nemôžu byť 0.', 'Beware: the hundreds digit cannot be 0.')], explain: [S('Rozoberieme, koľko možností má každé miesto, a potom ich spojíme (násobíme alebo spočítame prípady).', 'We count the options for each place and then combine them (multiply, or add cases).'), S(`Systematické spočítanie všetkých čísel od 100 do 999 dáva ${ans}.`, `Systematically counting all numbers from 100 to 999 gives ${ans}.`)] };
});

reg('pathgrid', 'combi', 2, c => {
  const { D, r } = c, R = clamp(ri(r, 2, 3 + Math.floor(D * 4)), 2, 7), C = clamp(ri(r, 3, 5 + Math.floor(D * 4)), 3, 8), nb = D < .35 ? 0 : ri(r, 1, lerp(1, 3, D));
  const blocked = new Set(); for (let t = 0; t < nb; t++) { const a = ri(r, 0, R - 1), b = ri(r, 0, C - 1); if ((a || b) && (a !== R - 1 || b !== C - 1)) blocked.add(a * C + b); }
  const dp = range(R).map(() => Array(C).fill(0)); dp[0][0] = 1;
  for (let a = 0; a < R; a++) for (let b = 0; b < C; b++) { if (blocked.has(a * C + b)) { dp[a][b] = 0; continue; } if (a || b) dp[a][b] = (a ? dp[a - 1][b] : 0) + (b ? dp[a][b - 1] : 0); }
  const ans = dp[R - 1][C - 1]; if (ans < 2) return null;
  const rows = range(R).map(a => range(C).map(b => a === 0 && b === 0 ? '🚩' : a === R - 1 && b === C - 1 ? '🏁' : blocked.has(a * C + b) ? '✖️' : '·'));
  return { title: S('Robot v mriežke', 'Robot on a grid'), type: 'number', visual: () => vGrid(rows),
    prompt: S(`🤖 Robot ide iba doprava alebo nadol z 🚩 do 🏁${nb ? ' (✖️ = zákaz)' : ''}. Koľko ciest vedie do cieľa?`, `🤖 The robot moves only right or down from 🚩 to 🏁${nb ? ' (✖️ = forbidden)' : ''}. How many paths lead to the goal?`),
    data: { answer: ans },
    hints: [S('Do každého políčka sa dá prísť zhora alebo zľava. Koľkými spôsobmi sa dostaneš do políčok v prvom riadku?', 'Every cell is reached from above or from the left. In how many ways can you reach the cells in the first row?'), S('Do políčka zapíš súčet počtov ciest do políčka nad ním a vľavo od neho.', 'Write in each cell the sum of the path counts of the cell above and the cell to its left.')],
    explain: [S('Do každého políčka zapíšeme, koľkými spôsobmi sa doň dá dostať: súčet políčka nad ním a vľavo od neho (zakázané políčka majú 0).', 'In each cell we write how many ways lead there: the sum of the cell above and the cell to the left (blocked cells have 0).'), S('Tabuľka počtov ciest:', 'Table of path counts:'), { text: S(`V cieli je ${ans}.`, `At the finish there is ${ans}.`), render: box => box.append(h('div', { html: vGrid(dp.map(rw => rw.map(x => x))) })) }] };
});

reg('pigeon', 'combi', 2, c => {
  const { D, k, r } = c, v = k % 4, j = Math.floor(k / 4);
  if (v === 0) { const col = clamp(2 + Math.floor(D * 4) + j % 3, 2, 8), need = clamp(2 + Math.floor(D * 3) + (j > 2 ? 1 : 0), 2, 6); return { title: S('Ponožky v tme', 'Socks in the dark'), type: 'number', prompt: S(`🧦 Ponožky ${col} farieb, je tma. Koľko ich vytiahneš, aby si mal určite ${need} rovnakej farby?`, `🧦 Socks of ${col} colours, it is dark. How many must you pull out to be sure of ${need} of one colour?`), data: { answer: (need - 1) * col + 1 },
    hints: [S('Predstav si najhoršiu možnosť – máš stále smolu.', 'Imagine the worst case – you are always unlucky.'), S(`Najhoršie je mať od každej farby o jednu menej ako ${need}.`, `The worst case is having one fewer than ${need} of every colour.`)], explain: [S(`Pri najhoršej smole máš od každej z ${col} farieb ${need - 1} ponožiek – to je ${(need - 1) * col}.`, `With the worst luck you hold ${need - 1} socks of each of the ${col} colours – that is ${(need - 1) * col}.`), S(`Ďalšia ponožka už musí dať ${need} rovnakých: ${(need - 1) * col} + 1 = ${(need - 1) * col + 1}.`, `The next sock must give ${need} of a kind: ${(need - 1) * col} + 1 = ${(need - 1) * col + 1}.`)] }; }
  if (v === 1) { const s = ri(r, 2, 4), need = clamp(2 + (j % 4), 2, 6); return { title: S('Karty a farby', 'Cards and suits'), type: 'number', prompt: S(`V balíčku sú karty štyroch farieb (♠ ♥ ♦ ♣), od každej farby je aspoň ${need * 2}. Kolko kariet musíš ťahať poslepiačky, aby si mal určite ${need} karty tej istej farby?`.replace('Kolko', 'Koľko'), `A deck has cards of four suits (♠ ♥ ♦ ♣), at least ${need * 2} of each. How many cards must you draw blindly to be sure of ${need} cards of the same suit?`), data: { answer: (need - 1) * 4 + 1 },
    hints: [S('Hľadáš najhorší možný priebeh ťahania.', 'Look for the worst possible way the draw can go.'), S(`V najhoršom prípade máš od každej farby ${need - 1} kariet.`, `In the worst case you hold ${need - 1} cards of every suit.`)], explain: [S(`Najhoršie: ${need - 1} kariet od každej zo 4 farieb, spolu ${(need - 1) * 4}.`, `Worst case: ${need - 1} cards of each of the 4 suits, ${(need - 1) * 4} in total.`), S(`Ďalšia karta teda určite dopočíta ${need} rovnakých: ${(need - 1) * 4 + 1}.`, `The next card must make ${need} of one suit: ${(need - 1) * 4 + 1}.`)] }; }
  if (v === 2) { const m = ri(r, 2, 12), n = 12 * m + ri(r, 1, 11) + j; return { title: S('Narodeniny v triede', 'Birthdays in class'), type: 'number', prompt: S(`V škole je ${n} žiakov. Rok má 12 mesiacov. Aký najväčší počet žiakov, ktorí majú narodeniny v tom istom mesiaci, je určite zaručený (aspoň v jednom mesiaci)?`, `A school has ${n} students. A year has 12 months. What is the largest number of students sharing a birth month that is guaranteed (in at least one month)?`), data: { answer: Math.ceil(n / 12) },
    hints: [S('Rozdeľ žiakov čo najrovnomernejšie do 12 mesiacov. Čo vyjde?', 'Spread the students as evenly as possible over 12 months. What do you get?'), S('Ak by mal každý mesiac najviac X žiakov, koľko by ich bolo najviac spolu?', 'If every month had at most X students, how many would there be at most in total?')], explain: [S(`${n} : 12 = ${(n / 12).toFixed(2)}…, takže niektorý mesiac musí mať aspoň ${Math.ceil(n / 12)} žiakov.`, `${n} : 12 = ${(n / 12).toFixed(2)}…, so some month must have at least ${Math.ceil(n / 12)} students.`), S('Keby mal každý mesiac menej, spolu by ich nebolo dosť. Tomu sa hovorí Dirichletov princíp.', 'If every month had fewer, there would not be enough in total. This is the pigeonhole principle.')] }; }
  const p = clamp(3 + j + Math.floor(D * 5), 3, 20); return { title: S('Rukavice v tme', 'Gloves in the dark'), type: 'number', prompt: S(`V skrini je ${p} rôznych párov rukavíc (každý pár inej farby, spolu ${2 * p} rukavíc ľavej a pravej). V tme ich ťaháš. Koľko rukavíc musíš aspoň vytiahnuť, aby si mal určite jeden celý pár (ľavú aj pravú rovnakej farby)?`, `A wardrobe holds ${p} different pairs of gloves (each pair its own colour, ${2 * p} gloves in all, left and right). You pull them out in the dark. What is the fewest you must take to be sure of a complete pair (left and right of one colour)?`), data: { answer: p + 1 },
    hints: [S('Najhoršie je, že ťaháš samé rôzne rukavice bez páru.', 'The worst case is pulling gloves with no matching partner.'), S(`Bez páru môžeš mať najviac jednu rukavicu od každej z ${p} farieb.`, `Without a pair you can hold at most one glove of each of the ${p} colours.`)], explain: [S(`V najhoršom prípade máš ${p} rukavíc, každú inej farby (všetky ľavé, napr.).`, `In the worst case you hold ${p} gloves, each a different colour (all left, say).`), S(`Každá ďalšia (${p + 1}.) rukavica už dá pár: ${p} + 1 = ${p + 1}.`, `The next one (number ${p + 1}) completes a pair: ${p} + 1 = ${p + 1}.`)] };
});

const MWORDS = ['ANNA', 'MAMA', 'OTTO', 'BANANA', 'LEVEL', 'KOKOS', 'ANANAS', 'PEPPER', 'TOMATO', 'SUMMER', 'COOKIE', 'ALABAMA', 'BOOKKEEPER', 'MISSISSIPPI', 'ABRAKADABRA', 'ASSASSIN', 'BALLOON', 'SUCCESS', 'PAPAYA', 'COFFEE'];
reg('multiset', 'combi', 5, c => {
  const { k, g, r, D } = c;
  if (k % 2 === 0) { const w = pickOf(MWORDS, Math.floor(k / 2), 'mw' + g), cnt2 = {}; w.split('').forEach(ch => cnt2[ch] = (cnt2[ch] || 0) + 1); let ans = fact(w.length); Object.values(cnt2).forEach(x => ans /= fact(x));
    return { title: S('Anagramy', 'Anagrams'), type: 'number', prompt: S(`Koľko rôznych „slov“ (aj nezmyselných) vznikne premiestnením všetkých písmen slova ${w}?`, `How many different “words” (nonsense allowed) can be made by rearranging all the letters of ${w}?`), data: { answer: ans },
      hints: [S('Najprv predstav, že všetky písmená sú rôzne. Koľko je usporiadaní?', 'First imagine all letters are different. How many arrangements are there?'), S('Rovnaké písmená sa dajú vzájomne vymeniť – každé usporiadanie si tak započítal viackrát.', 'Identical letters can be swapped – so you counted each arrangement several times.')],
      explain: [S(`Keby boli všetky písmená rôzne, bolo by ${w.length}! = ${fact(w.length)} usporiadaní.`, `If all letters were different there would be ${w.length}! = ${fact(w.length)} arrangements.`), S(`Opakujúce sa písmená vydelíme faktoriálom ich počtu: ${Object.entries(cnt2).filter(([, x]) => x > 1).map(([ch, x]) => `${ch}: ${x}!`).join(', ') || '–'}. Výsledok je ${ans}.`, `Divide by the factorial of each repeated letter: ${Object.entries(cnt2).filter(([, x]) => x > 1).map(([ch, x]) => `${ch}: ${x}!`).join(', ') || '–'}. The result is ${ans}.`)] }; }
  const a = ri(r, 1, 4), b = ri(r, 1, 4), cc = ri(r, 1, 3) + Math.floor(D * 2), n = a + b + cc, ans = fact(n) / (fact(a) * fact(b) * fact(cc));
  return { title: S('Korálky v rade', 'Beads in a row'), type: 'number', prompt: S(`Na šnúrke je v rade ${a + b + cc} korálok: červené – ${a}, modré – ${b}, zelené – ${cc} (korálky rovnakej farby sa nerozlišujú). Koľko rôznych vzorov možno vytvoriť?`, `A string holds ${a + b + cc} beads in a row: red – ${a}, blue – ${b}, green – ${cc} (beads of one colour look the same). How many different patterns are possible?`), data: { answer: ans },
    hints: [S('Najprv zvoľ miesta pre červené. Koľkými spôsobmi?', 'First choose the places for the red ones. In how many ways?'), S('Potom z ostatných miest vyber miesta pre modré.', 'Then among the remaining places choose the blue ones.')],
    explain: [S(`Miesta pre červené: C(${n}, ${a}) = ${binom(n, a)}.`, `Places for red: C(${n}, ${a}) = ${binom(n, a)}.`), S(`Z ostatných ${n - a} miest vyberieme modré: C(${n - a}, ${b}) = ${binom(n - a, b)}; zelené dostanú zvyšok.`, `From the remaining ${n - a} places choose blue: C(${n - a}, ${b}) = ${binom(n - a, b)}; green takes the rest.`), S(`Spolu ${binom(n, a)} · ${binom(n - a, b)} = ${ans}.`, `In total ${binom(n, a)} · ${binom(n - a, b)} = ${ans}.`)] };
});

/* ---------- numbers & patterns ---------- */
Object.assign(SEQ, {
  dbl1(r) { const a = ri(r, 1, 5), sg = r() < .5 ? 1 : -1, terms = [a]; for (let i = 1; i < 5; i++) terms.push(terms[i - 1] * 2 + sg); const ans = terms[4] * 2 + sg; const w = sg > 0 ? '+ 1' : '− 1';
    return { terms, ans, h: [S('Skús, či nasledujúce číslo nie je dvojnásobok predchádzajúceho s malou úpravou.', 'Check whether each number is double the previous one with a small tweak.'), S(`Každé číslo je 2 · (predchádzajúce) ${w}.`, `Each number is 2 · (previous) ${w}.`)], ex: [S(`${terms[0]} · 2 ${w} = ${terms[1]}, ${terms[1]} · 2 ${w} = ${terms[2]} …`, `${terms[0]} · 2 ${w} = ${terms[1]}, ${terms[1]} · 2 ${w} = ${terms[2]} …`), S(`Ďalšie: ${terms[4]} · 2 ${w} = ${ans}.`, `Next: ${terms[4]} · 2 ${w} = ${ans}.`)] }; },
  tri(r) { const s = ri(r, 1, 6), T = n => n * (n + 1) / 2, terms = range(5).map(i => T(s + i));
    return { terms, ans: T(s + 5), h: [S('Pozri sa na rozdiely medzi susednými číslami. Aké sú?', 'Look at the differences between neighbours. What are they?'), S('Rozdiely rastú o 1 – sú to trojuholníkové čísla.', 'The differences grow by 1 – these are triangular numbers.')], ex: [S(`Rozdiely: ${terms.slice(1).map((x, i) => x - terms[i]).join(', ')} – každý je o 1 väčší.`, `Differences: ${terms.slice(1).map((x, i) => x - terms[i]).join(', ')} – each is 1 bigger.`), S(`Ďalší rozdiel je ${s + 5}, preto ${terms[4]} + ${s + 5} = ${T(s + 5)}.`, `The next difference is ${s + 5}, so ${terms[4]} + ${s + 5} = ${T(s + 5)}.`)] }; },
  second(r) { const p = ri(r, 1, 8), q = ri(r, 0, 4), cc = ri(r, 1, 3), f = i => p + q * i + cc * i * (i - 1) / 2, terms = range(5).map(f);
    return { terms, ans: f(5), h: [S('Pozri sa na rozdiely a potom na rozdiely rozdielov.', 'Look at the differences and then at the differences of the differences.'), S(`Rozdiely rozdielov sú stále ${cc}.`, `The differences of the differences are always ${cc}.`)], ex: [S(`Rozdiely: ${terms.slice(1).map((x, i) => x - terms[i]).join(', ')}; ich rozdiely sú stále ${cc}.`, `Differences: ${terms.slice(1).map((x, i) => x - terms[i]).join(', ')}; their differences are always ${cc}.`), S(`Ďalší rozdiel je ${f(5) - terms[4]}, takže ďalšie číslo je ${f(5)}.`, `The next difference is ${f(5) - terms[4]}, so the next number is ${f(5)}.`)] }; }
});
SEQ_TIERS[2].push('dbl1'); SEQ_TIERS[3].push('dbl1', 'tri'); SEQ_TIERS[4].push('tri', 'second'); SEQ_TIERS[5].push('second', 'tri');
reg('seq', 'seq', 2, c => {
  const tier = clamp(1 + Math.floor(c.D * 4.99), 1, 5), t = genSeq('seq:' + c.g + ':' + c.k + ':' + Math.floor(c.r() * 1e9), tier, bandOf(c.g));
  return { title: t.title, prompt: t.prompt, visual: t.visual, type: 'number', data: t.data, hints: t.hints, explain: t.explain };
});

reg('magic', 'seq', 2, c => {
  const { r, D } = c, Lo = [[2, 7, 6], [9, 5, 1], [4, 3, 8]], x = ri(r, 0, lerp(2, 40, D)), y = ri(r, 1, lerp(1, 7, D));
  let sq = Lo.map(rw => rw.map(v => x + y * v));
  if (r() < .5) sq = sq[0].map((_, i) => sq.map(rw => rw[i])); if (r() < .5) sq = sq.slice().reverse(); if (r() < .5) sq = sq.map(rw => rw.slice().reverse());
  const S0 = 3 * x + 15 * y, hcount = clamp(lerp(1, 4, D) + ri(r, 0, 1), 1, 4);
  for (let tries = 0; tries < 60; tries++) {
    const cells = shuffle(range(9), r).slice(0, hcount), known = sq.map(rw => rw.slice()); cells.forEach(i => known[Math.floor(i / 3)][i % 3] = null);
    const lines = [...range(3).map(i => range(3).map(j => [i, j])), ...range(3).map(j => range(3).map(i => [i, j])), [[0, 0], [1, 1], [2, 2]], [[0, 2], [1, 1], [2, 0]]];
    const full = lines.find(l => l.every(([a, b]) => known[a][b] != null)); if (!full) continue;
    const mag = full.reduce((s, [a, b]) => s + known[a][b], 0), derived = []; let ch = true;
    while (ch) { ch = false; for (const l of lines) { const un = l.filter(([a, b]) => known[a][b] == null); if (un.length === 1) { const [a, b] = un[0], v = mag - l.filter(([p, q]) => known[p][q] != null).reduce((s, [p, q]) => s + known[p][q], 0), letter = 'ABCD'[cells.indexOf(a * 3 + b)]; derived.push({ letter, expr: `${mag} − (${l.filter(([p, q]) => known[p][q] != null).map(([p, q]) => known[p][q]).join(' + ')}) = ${v}` }); known[a][b] = v; ch = true; } } }
    if (known.some((rw, a2) => rw.some((v, b2) => v == null || v !== sq[a2][b2]))) continue;
    const letters = cells.map((i, idx) => 'ABCD'[idx]), disp = sq.map((rw, a) => rw.map((v, b) => { const idx = cells.indexOf(a * 3 + b); return idx >= 0 ? `<b>${'ABCD'[idx]}</b>` : v; }));
    const target = ri(r, 0, hcount - 1);
    return { title: S('Magický štvorec', 'Magic square'), type: 'number', visual: () => vGrid(disp),
      prompt: S(`V magickom štvorci majú všetky riadky, všetky stĺpce aj obe uhlopriečky rovnaký súčet. Aké číslo patrí na miesto ${letters[target]}?`, `In a magic square all rows, all columns and both diagonals have the same sum. Which number belongs at ${letters[target]}?`),
      data: { answer: sq[Math.floor(cells[target] / 3)][cells[target] % 3] },
      hints: [S('Nájdi riadok, stĺpec alebo uhlopriečku, v ktorej poznáš všetky čísla – to je magický súčet.', 'Find a row, column or diagonal where all numbers are known – that is the magic sum.'), S('V línii s jedným neznámym číslom ho doplníš ako rozdiel magického súčtu a súčtu ostatných.', 'In a line with one unknown, it equals the magic sum minus the sum of the others.')],
      explain: [S(`Magický súčet je ${mag} (z úplne známej línie).`, `The magic sum is ${mag} (from a fully known line).`), both(l => derived.map(d => `${d.letter} = ${d.expr}`).join(' • '))] };
  }
  return null;
});

reg('symbols', 'seq', 2, c => {
  const { r, D } = c, sym = shuffle(['🍎', '🍌', '🍇', '🍓', '🍒', '🍐', '🥝', '🍋', '🍑'], r).slice(0, D > .65 ? 4 : 3), mx = lerp(5, 18, D), n = sym.length;
  const v = []; while (v.length < n) { const x = ri(r, 1, mx); if (!v.includes(x)) v.push(x); }
  const eqs = [], co = [];
  for (let i = 0; i < n; i++) { const cf = range(n).map(j => j === i ? ri(r, 1, 3) : (j < i && r() < (D > .4 ? .6 : .4) ? ri(r, 1, 2) : 0)); if (i === 0 && cf[0] < 2) cf[0] = 2; co.push(cf); eqs.push(`${cf.map((m, j) => m ? range(m).map(() => sym[j]).join('+') : '').filter(Boolean).join('+')} = ${cf.reduce((s, m, j) => s + m * v[j], 0)}`); }
  const q = range(n).map(() => ri(r, 1, 2)); q[0] = Math.max(q[0], 1); const ans = q.reduce((s, m, j) => s + m * v[j], 0);
  return { title: S('Ovocné rovnice', 'Fruit equations'), type: 'number', visual: () => vEqs(eqs),
    prompt: S(`Rovnaké ovocie = rovnaké číslo. Koľko je ${q.map((m, j) => range(m).map(() => sym[j]).join('+')).join('+')}?`, `Same fruit = same number. How much is ${q.map((m, j) => range(m).map(() => sym[j]).join('+')).join('+')}?`),
    data: { answer: ans },
    hints: [S('Začni rovnicou, v ktorej je iba jeden druh ovocia.', 'Start with the equation containing only one kind of fruit.'), S('Keď poznáš hodnotu jedného ovocia, dosaď ju do ďalšej rovnice.', 'Once you know one fruit’s value, substitute it into the next equation.')],
    explain: [S('Rovnice riešime postupne, od tej s jediným ovocím:', 'We solve the equations in order, starting with the single-fruit one:'), both(l => sym.map((s, j) => `${s} = ${v[j]}`).join(', ')), S(`Dosadíme do otázky a dostaneme ${ans}.`, `Substituting into the question gives ${ans}.`)] };
});

function cryptSolve(ops, letters, lead, limit) {
  let found = 0, sol = null; const used = Array(10).fill(false), asg = {};
  const val = w => w.split('').reduce((s, ch) => s * 10 + asg[ch], 0);
  const rec = i => {
    if (found > limit) return;
    if (i === letters.length) { if (ops.ok(val)) { found++; sol = { ...asg }; } return; }
    for (let d = 0; d < 10; d++) { if (used[d] || (d === 0 && lead.has(letters[i]))) continue; used[d] = true; asg[letters[i]] = d; rec(i + 1); used[d] = false; }
  };
  rec(0); return { found, sol };
}
reg('cryptarithm', 'crypto', 3, c => {
  const { r, D } = c, ABC = 'ABCDEFGHKLMNPRSTXZ'.split('');
  for (let tries = 0; tries < 80; tries++) {
    const op = D < .45 ? '+' : pick(['+', '+', '−', '×'], r), x = ri(r, 10, 99), y = op === '×' ? ri(r, 2, 9) : ri(r, D < .3 ? 2 : 5, op === '−' ? Math.min(x - 1, 99) : 99);
    const z = op === '+' ? x + y : op === '−' ? x - y : x * y; if (z < 1 || z > 999) continue;
    const digs = [...new Set((x + '' + y + z).split('').map(Number))]; if (digs.length < 3 || digs.length > (D < .5 ? 4 : 5)) continue;
    const letters = shuffle(ABC, r).slice(0, digs.length), map = {}; digs.forEach((d, i) => map[d] = letters[i]);
    const enc = n => String(n).split('').map(d => map[d]).join(''), X = enc(x), Y = enc(y), Z = enc(z);
    const lead = new Set([X[0], Y.length > 1 ? Y[0] : null, Z.length > 1 ? Z[0] : null].filter(Boolean)), L2 = [...new Set((X + Y + Z).split(''))];
    const f = val => { const a = val(X), b = val(Y), cz = val(Z); return op === '+' ? a + b === cz : op === '−' ? a - b === cz : a * b === cz; };
    const res = cryptSolve({ ok: f }, L2, lead, 1); if (res.found !== 1) continue;
    const ask = pick(L2, r), sol = res.sol;
    return { title: S('Kryptogram', 'Cryptarithm'), type: 'number', visual: () => `<div class="eqbig">${X} ${op} ${Y} = ${Z}</div>`,
      prompt: S('Rôzne písmená znamenajú rôzne číslice, rovnaké písmená rovnaké číslice a číslo nezačína nulou. Ktorá číslica sa skrýva za písmenom ' + ask + '?', 'Different letters stand for different digits, equal letters for equal digits, and no number starts with zero. Which digit hides behind the letter ' + ask + '?'),
      data: { answer: sol[ask] },
      hints: [S('Začni miestom, kde je odpoveď takmer istá – napríklad prvá číslica výsledku pri sčitovaní.', 'Start where the answer is almost certain – e.g. the first digit of the result in an addition.'), S('Skúšaj možnosti a zakaždým over, či sa zhodujú všetky stĺpce.', 'Try options and check every column each time.')],
      explain: [S('Postupne vylučujeme číslice, ktoré by viedli k sporu.', 'We rule out digits that would lead to a contradiction.'), both(l => (l === 'sk' ? 'Jediné riešenie: ' : 'The only solution: ') + L2.map(ch => `${ch} = ${sol[ch]}`).join(', ') + ` (${x} ${op} ${y} = ${z}).`)] };
  }
  return null;
});

/* ---------- space & shapes ---------- */
reg('paintedcube', 'spatial', 2, c => {
  const { D, k, r } = c, f = [3, 2, 1, 0][k % 4], j = Math.floor(k / 4) + ri(r, 0, 2), n = clamp(lerp(3, 7, D) + j, 3, 14), cub = D < .5 || k % 2 === 0, a = n, b = cub ? n : n + 1 + (j % 2), cc = cub ? n : Math.max(3, n - 1);
  let ans = 0; for (let x = 0; x < a; x++) for (let y = 0; y < b; y++) for (let z = 0; z < cc; z++) if ((x === 0 || x === a - 1) + (y === 0 || y === b - 1) + (z === 0 || z === cc - 1) === f) ans++;
  const fq = [S('žiadnu natretú stenu', 'no painted face'), S('práve 1 natretú stenu', 'exactly 1 painted face'), S('práve 2 natreté steny', 'exactly 2 painted faces'), S('práve 3 natreté steny', 'exactly 3 painted faces')][f];
  const formula = [S(`Kocky vo vnútri: (${a}−2)·(${b}−2)·(${cc}−2) = ${ans}.`, `Interior cubes: (${a}−2)·(${b}−2)·(${cc}−2) = ${ans}.`), S(`Kocky v stredoch stien: 2·((${a}−2)(${b}−2) + (${b}−2)(${cc}−2) + (${a}−2)(${cc}−2)) = ${ans}.`, `Cubes in the middle of faces: 2·((${a}−2)(${b}−2) + (${b}−2)(${cc}−2) + (${a}−2)(${cc}−2)) = ${ans}.`), S(`Kocky na hranách bez rohov: 4·((${a}−2) + (${b}−2) + (${cc}−2)) = ${ans}.`, `Edge cubes without corners: 4·((${a}−2) + (${b}−2) + (${cc}−2)) = ${ans}.`), S('Kocky v rohoch: kváder má 8 rohov.', 'Corner cubes: a box has 8 corners.')][f];
  return { title: cub ? S('Natretá kocka', 'The painted cube') : S('Natretý kváder', 'The painted box'), type: 'number',
    prompt: S(`${cub ? `Veľká kocka ${a}×${a}×${a} je zložená` : `Kváder ${a}×${b}×${cc} je zložený`} z malých kociek 1×1×1 a zvonku ${cub ? 'celá natretá' : 'celý natretý'}. Rozoberieme ${cub ? 'ju' : 'ho'} na malé kocky. Koľko malých kociek má ${fq.sk}?`, `${cub ? `A big ${a}×${a}×${a} cube` : `A ${a}×${b}×${cc} box`} is built from 1×1×1 cubes and painted all over the outside. We take it apart. How many small cubes have ${fq.en}?`),
    data: { answer: ans },
    hints: [S('Ktoré malé kocky sú v rohoch? Ktoré na hranách? Ktoré v stenách a ktoré vo vnútri?', 'Which small cubes are in corners? On edges? In faces? Inside?'), S('Počet natretých stien závisí od polohy kocky: roh 3, hrana 2, stena 1, vnútro 0.', 'The number of painted faces depends on position: corner 3, edge 2, face 1, interior 0.')],
    explain: [S('Poloha kocky určuje počet natretých stien: roh = 3, hrana = 2, stena = 1, vnútro = 0.', 'Position decides the painted faces: corner = 3, edge = 2, face = 1, interior = 0.'), formula, S(`Odpoveď: ${ans}.`, `Answer: ${ans}.`)] };
});

const vSquares = (n, m) => `<svg class="gridsvg" viewBox="0 0 ${m * 36 + 8} ${n * 36 + 8}" role="img" aria-label="${n}×${m}">${range(n + 1).map(i => `<line x1="4" y1="${i * 36 + 4}" x2="${m * 36 + 4}" y2="${i * 36 + 4}" stroke="#14213d" stroke-width="2.5"/>`).join('')}${range(m + 1).map(i => `<line x1="${i * 36 + 4}" y1="4" x2="${i * 36 + 4}" y2="${n * 36 + 4}" stroke="#14213d" stroke-width="2.5"/>`).join('')}</svg>`;
reg('squares', 'spatial', 2, c => {
  const { D, k, r } = c, v = D < .4 ? k % 2 : k % 3, j = Math.floor(k / (D < .4 ? 2 : 3)) + ri(r, 0, 2), n = clamp(2 + j + Math.floor(D * 3), 2, 9);
  if (v === 0) { let ans = 0; for (let s = 1; s <= n; s++) ans += (n - s + 1) ** 2;
    return { title: S('Koľko štvorcov?', 'How many squares?'), type: 'number', visual: () => vSquares(n, n), prompt: S(`Koľko štvorcov (aj veľkých) nájdeš v mriežke ${n} × ${n}?`, `How many squares (big ones too) can you find in the ${n} × ${n} grid?`), data: { answer: ans },
      hints: [S('Najprv spočítaj štvorčeky 1×1. Potom 2×2. Čo ďalej?', 'First count the 1×1 squares. Then the 2×2 ones. What next?'), S('Štvorcov veľkosti s je (n − s + 1)². Spočítaj všetky veľkosti.', 'Squares of size s number (n − s + 1)². Add up all sizes.')],
      explain: [S('Počítame podľa veľkosti štvorca. Veľkosť s sa dá umiestniť (n − s + 1)² spôsobmi.', 'We count by square size. Size s fits in (n − s + 1)² positions.'), S(`Súčet: ${range(n).map(i => (n - i) ** 2).join(' + ')} = ${ans}.`, `Sum: ${range(n).map(i => (n - i) ** 2).join(' + ')} = ${ans}.`)] }; }
  const m = clamp(n + 1 + (j % 2), 3, 10);
  if (v === 1) { let ans = 0; for (let s = 1; s <= Math.min(n, m); s++) ans += (n - s + 1) * (m - s + 1);
    return { title: S('Štvorce v obdĺžniku', 'Squares in a rectangle'), type: 'number', visual: () => vSquares(n, m), prompt: S(`Koľko štvorcov (aj veľkých) nájdeš v mriežke ${n} × ${m}?`, `How many squares (big ones too) can you find in the ${n} × ${m} grid?`), data: { answer: ans },
      hints: [S('Štvorce veľkosti 1×1 sú ${n}·${m}. Koľko je štvorcov 2×2?'.replace('${n}·${m}', n * m), `There are ${n * m} squares of size 1×1. How many 2×2 squares are there?`), S('Štvorec veľkosti s sa dá umiestniť (riadky − s + 1) · (stĺpce − s + 1) spôsobmi.', 'A square of size s fits in (rows − s + 1) · (columns − s + 1) positions.')],
      explain: [S('Počítame podľa veľkosti štvorca s = 1, 2, … až po menší rozmer.', 'We count by square size s = 1, 2, … up to the smaller dimension.'), S(`Súčet: ${range(Math.min(n, m)).map(i => `${n - i}·${m - i}`).join(' + ')} = ${ans}.`, `Sum: ${range(Math.min(n, m)).map(i => `${n - i}·${m - i}`).join(' + ')} = ${ans}.`)] }; }
  const rn = clamp(n, 2, 6), rm = clamp(m, 3, 7), ans = binom(rn + 1, 2) * binom(rm + 1, 2);
  return { title: S('Koľko obdĺžnikov?', 'How many rectangles?'), type: 'number', visual: () => vSquares(rn, rm), prompt: S(`Mriežka má ${rn} riadkov a ${rm} stĺpcov. Koľko obdĺžnikov (štvorce sú tiež obdĺžniky) sa v nej dá nájsť?`, `The grid has ${rn} rows and ${rm} columns. How many rectangles (squares count too) can you find in it?`), data: { answer: ans },
    hints: [S('Obdĺžnik je určený dvoma vodorovnými a dvoma zvislými čiarami.', 'A rectangle is fixed by two horizontal and two vertical lines.'), S(`Koľkými spôsobmi vyberieš 2 z ${rn + 1} vodorovných a 2 z ${rm + 1} zvislých čiar?`, `In how many ways can you choose 2 of the ${rn + 1} horizontal and 2 of the ${rm + 1} vertical lines?`)],
    explain: [S(`Vodorovných čiar je ${rn + 1}, zvislých ${rm + 1}.`, `There are ${rn + 1} horizontal and ${rm + 1} vertical lines.`), S(`Dve vodorovné: C(${rn + 1},2) = ${binom(rn + 1, 2)}, dve zvislé: C(${rm + 1},2) = ${binom(rm + 1, 2)}. Spolu ${ans}.`, `Two horizontal: C(${rn + 1},2) = ${binom(rn + 1, 2)}, two vertical: C(${rm + 1},2) = ${binom(rm + 1, 2)}. In total ${ans}.`)] };
});

reg('towers', 'spatial', 2, c => {
  const { r, D } = c, g = D < .45 ? 3 : D < .8 ? 4 : 5, hmax = lerp(2, 5, D), H = range(g).map(() => range(g).map(() => ri(r, 0, hmax))), q = D < .35 ? 'total' : D < .7 ? (r() < .5 ? 'total' : 'front') : pick(['front', 'surface', 'surface'], r);
  const total = H.flat().reduce((a, b) => a + b, 0), front = range(g).reduce((s, x) => s + Math.max(...H.map(row => row[x])), 0);
  let surf = 0; for (let a = 0; a < g; a++) for (let b = 0; b < g; b++) { const h2 = H[a][b]; if (!h2) continue; surf += 1; [[1, 0], [-1, 0], [0, 1], [0, -1]].forEach(([da, db]) => { const nb = H[a + da]?.[b + db] ?? 0; surf += Math.max(0, h2 - nb); }); }
  const ans = q === 'total' ? total : q === 'front' ? front : surf; if (total < 4) return null;
  return { title: S('Stavba z kociek', 'Cube building'), type: 'number', visual: () => vTowers(H),
    prompt: q === 'total' ? S('🧱 Čísla ukazujú výšku veží. Koľko kociek je spolu?', '🧱 The numbers show tower heights. How many cubes in all?')
      : q === 'front' ? S('🧱 Pozeráš spredu (od spodného okraja). Koľko štvorčekov vidíš?', '🧱 You look from the front (bottom edge). How many squares do you see?')
        : S('🧱 Natrieme stavbu zhora aj zo strán (nie dno). Koľko štvorčekov bude natretých?', '🧱 We paint the building on top and sides (not the bottom). How many squares get painted?'),
    data: { answer: ans },
    hints: q === 'total' ? [S('Každé číslo je jedna veža. Čo s nimi urobíš?', 'Each number is one tower. What do you do with them?'), S('Sčítaj všetky čísla v tabuľke.', 'Add all numbers in the table.')]
      : q === 'front' ? [S('Zo predu vidíš pre každý stĺpec iba najvyššiu vežu.', 'From the front you only see the tallest tower of each column.'), S('Vezmi z každého stĺpca najväčšie číslo a sčítaj ich.', 'Take the biggest number from each column and add them.')]
        : [S('Spočítaj osobitne vrchy (každá veža má jeden) a boky.', 'Count tops (one per tower) and sides separately.'), S('Bok veže je viditeľný iba nad susednou vežou: ide o rozdiel výšok (alebo o celú výšku pri okraji).', 'A side is visible only above the neighbouring tower: the height difference (or the full height at the edge).')],
    explain: q === 'total' ? [S('Každé číslo hovorí, z koľkých kociek je veža.', 'Each number says how many cubes the tower has.'), S(`Súčet všetkých čísel je ${total}.`, `The sum of all numbers is ${total}.`)]
      : q === 'front' ? [S('Zo predu zakrýva nižšia veža vyššia, ak je pred ňou – vidíme len najvyššiu v stĺpci.', 'From the front a taller tower hides shorter ones behind it – we see only the tallest in each column.'), S(`Súčet maxím stĺpcov je ${front}.`, `The sum of the column maxima is ${front}.`)]
        : [S('Vrchy: počet neprázdnych políčok. Boky: pri každej strane veže rozdiel výšky voči susedovi (okraj má susedu výšky 0).', 'Tops: the number of non-empty cells. Sides: for each side of a tower the height difference to its neighbour (the border counts as height 0).'), S(`Spolu ${surf} natretých štvorčekov.`, `${surf} painted faces in total.`)] };
});

reg('areas', 'geom', 2, c => {
  const { r, D, k } = c, v = k % 5, j = Math.floor(k / 5), sc = lerp(3, 14, D);
  if (v === 0) { const W = ri(r, 5, sc + 6) + j % 4, Hh = ri(r, 4, sc + 4) + (j + 1) % 3, w = ri(r, 1, W - 2), hh = ri(r, 1, Hh - 2), ask = k % 2 ? 'area' : 'per'; const ans = ask === 'area' ? W * Hh - w * hh : 2 * (W + Hh);
    return { title: S('Tvar v tvare L', 'L-shaped figure'), type: 'number', prompt: S(`Z obdĺžnika ${W} cm × ${Hh} cm sa vystrihol z rohu obdĺžnik ${w} cm × ${hh} cm. Aký je ${ask === 'area' ? 'obsah' : 'obvod'} zostávajúceho tvaru?`, `A ${w} cm × ${hh} cm rectangle is cut from the corner of a ${W} cm × ${Hh} cm rectangle. What is the ${ask === 'area' ? 'area' : 'perimeter'} of the remaining shape?`), data: { answer: ans, unit: ask === 'area' ? 'cm²' : 'cm' },
      hints: ask === 'area' ? [S('Obsah celého obdĺžnika mínus obsah vystrihnutej časti.', 'The area of the whole rectangle minus the cut-out part.'), S('Vypočítaj oba obdĺžniky osobitne.', 'Work out both rectangles separately.')] : [S('Skús si tvar nakresliť. Posúvaním strán sa dá obvod zjednodušiť.', 'Draw the shape. Sliding the sides can simplify the perimeter.'), S('Obvod tvaru L je rovnaký ako obvod pôvodného obdĺžnika.', 'The perimeter of an L-shape equals that of the original rectangle.')],
      explain: ask === 'area' ? [S(`Celý obdĺžnik: ${W} · ${Hh} = ${W * Hh} cm².`, `Whole rectangle: ${W} · ${Hh} = ${W * Hh} cm².`), S(`Vystrihnutá časť: ${w} · ${hh} = ${w * hh} cm². Zostáva ${ans} cm².`, `Cut-out: ${w} · ${hh} = ${w * hh} cm². What remains: ${ans} cm².`)] : [S('Vystrihnutím z rohu sa obvod nezmení: nové strany sa dajú presunúť na pôvodné.', 'Cutting a corner leaves the perimeter unchanged: the new sides slide onto the old ones.'), S(`Obvod = 2 · (${W} + ${Hh}) = ${ans} cm.`, `Perimeter = 2 · (${W} + ${Hh}) = ${ans} cm.`)] }; }
  if (v === 1) { const s = ri(r, 3, sc + 3) + j, m = ri(r, 2, 3); return { title: S('Zväčšený štvorec', 'Enlarged square'), type: 'number', prompt: S(`Štvorec má obsah ${s * s} cm². Každú jeho stranu ${m === 2 ? 'zdvojnásobíme' : 'strojnásobíme'}. Aký obsah bude mať nový štvorec?`, `A square has area ${s * s} cm². Every side is ${m === 2 ? 'doubled' : 'tripled'}. What is the area of the new square?`), data: { answer: s * s * m * m, unit: 'cm²' },
    hints: [S('Aká dlhá je strana pôvodného štvorca?', 'How long is the side of the original square?'), S('Nová strana je zväčšená, obsah je strana krát strana.', 'The new side is enlarged; the area is side times side.')], explain: [S(`Pôvodná strana: ${s} cm. Nová: ${s * m} cm.`, `Original side: ${s} cm. New side: ${s * m} cm.`), S(`Nový obsah ${s * m} · ${s * m} = ${s * s * m * m} cm² (${m * m}-krát väčší).`, `New area ${s * m} · ${s * m} = ${s * s * m * m} cm² (${m * m} times bigger).`)] }; }
  if (v === 2) { const a = ri(r, 4, sc + 6) + j % 3, b = ri(r, 3, sc + 4) + (j + 1) % 3; return { title: S('Obdĺžnik z obvodu', 'Rectangle from perimeter'), type: 'number', prompt: S(`Obdĺžnik má obvod ${2 * (a + b)} cm a jedna jeho strana má ${a} cm. Aký je jeho obsah?`, `A rectangle has a perimeter of ${2 * (a + b)} cm and one side of ${a} cm. What is its area?`), data: { answer: a * b, unit: 'cm²' },
    hints: [S('Obvod je 2 · (a + b). Koľko je a + b?', 'The perimeter is 2 · (a + b). What is a + b?'), S(`Poznáš a = ${a}. Aká je druhá strana?`, `You know a = ${a}. What is the other side?`)], explain: [S(`a + b = ${a + b} (polovica obvodu).`, `a + b = ${a + b} (half the perimeter).`), S(`Druhá strana: ${a + b} − ${a} = ${b} cm, obsah ${a} · ${b} = ${a * b} cm².`, `The other side: ${a + b} − ${a} = ${b} cm, area ${a} · ${b} = ${a * b} cm².`)] }; }
  if (v === 3) { const a = ri(r, 3, sc + 4) * 2, h2 = ri(r, 2, sc), t = ri(r, 1, 2); return { title: S('Obsah trojuholníka', 'Triangle area'), type: 'number', prompt: S(`Trojuholník má základňu ${a} cm a výšku na ňu ${h2 * 2 * t} cm. Aký je jeho obsah?`, `A triangle has a base of ${a} cm and a height to it of ${h2 * 2 * t} cm. What is its area?`), data: { answer: a * h2 * t, unit: 'cm²' },
    hints: [S('Trojuholník je polovica vhodného obdĺžnika.', 'A triangle is half of a suitable rectangle.'), S('Obsah = základňa · výška : 2.', 'Area = base · height : 2.')], explain: [S('Obsah trojuholníka = (základňa · výška) : 2.', 'Triangle area = (base · height) : 2.'), S(`(${a} · ${h2 * 2 * t}) : 2 = ${a * h2 * t} cm².`, `(${a} · ${h2 * 2 * t}) : 2 = ${a * h2 * t} cm².`)] }; }
  const a = ri(r, 8, sc + 12) + j, b = ri(r, 6, sc + 8), t = ri(r, 1, 3), outer = a * b, inner = (a - 2 * t) * (b - 2 * t); if (inner <= 0) return null;
  return { title: S('Rám obrazu', 'Picture frame'), type: 'number', prompt: S(`Obraz má vonkajšie rozmery ${a} cm × ${b} cm a rám široký ${t} cm po celom obvode. Aký je obsah samotného rámu (bez vnútornej plochy)?`, `A picture measures ${a} cm × ${b} cm outside, with a frame ${t} cm wide all around. What is the area of the frame itself (without the inner part)?`), data: { answer: outer - inner, unit: 'cm²' },
    hints: [S('Aké rozmery má vnútorná plocha?', 'What are the dimensions of the inner part?'), S(`Z každej strany ubudne ${t} cm – spolu ${2 * t} cm na jeden rozmer.`, `${t} cm goes from each side – ${2 * t} cm per dimension.`)], explain: [S(`Vnútro: (${a} − ${2 * t}) × (${b} − ${2 * t}) = ${a - 2 * t} × ${b - 2 * t} = ${inner} cm².`, `Inner part: (${a} − ${2 * t}) × (${b} − ${2 * t}) = ${a - 2 * t} × ${b - 2 * t} = ${inner} cm².`), S(`Rám = ${outer} − ${inner} = ${outer - inner} cm².`, `Frame = ${outer} − ${inner} = ${outer - inner} cm².`)] };
});

/* ---------- olympiad-style ---------- */
reg('algebra', 'algebra', 2, c => {
  const { r, D, k, g } = c, nv = g >= 6 ? 6 : 5, v = k % nv, j = Math.floor(k / nv), sc = lerp(4, 40, D);
  if (v === 0) { const x = ri(r, 2, sc) + j, a = ri(r, 2, 4 + Math.floor(D * 6)), b = ri(r, 1, sc); return { title: S('Myslím si číslo', 'I think of a number'), type: 'number', prompt: S(`Myslím si číslo. Keď ho vynásobím ${a} a pripočítam ${b}, dostanem ${a * x + b}. Aké číslo si myslím?`, `I think of a number. When I multiply it by ${a} and add ${b} I get ${a * x + b}. What is my number?`), data: { answer: x },
    hints: [S('Postupuj odzadu: čo urobíš s výsledkom, aby si zrušil posledný krok?', 'Work backwards: what do you do to the result to undo the last step?'), S(`Najprv odpočítaj ${b}, potom deľ ${a}.`, `First subtract ${b}, then divide by ${a}.`)], explain: [S(`${a * x + b} − ${b} = ${a * x}.`, `${a * x + b} − ${b} = ${a * x}.`), S(`${a * x} : ${a} = ${x}.`, `${a * x} : ${a} = ${x}.`)] }; }
  if (v === 1) { const n = ri(r, 3, 5 + Math.floor(D * 4)), s0 = ri(r, 2, sc * 2) + j, sum = n * s0 + n * (n - 1) / 2; return { title: S('Čísla za sebou', 'Numbers in a row'), type: 'number', prompt: S(`Súčet ${n} po sebe idúcich celých čísel je ${sum}. Aké je najväčšie z nich?`, `The sum of ${n} consecutive integers is ${sum}. What is the largest of them?`), data: { answer: s0 + n - 1 },
    hints: [S('Označ najmenšie číslo n. Ako zapíšeš ostatné?', 'Call the smallest number n. How do you write the others?'), S(`n, n+1, …, n+${n - 1}: čomu sa rovná súčet?`, `n, n+1, …, n+${n - 1}: what is the sum?`)], explain: [S(`Súčet je ${n}·n + ${n * (n - 1) / 2} = ${sum}.`, `The sum is ${n}·n + ${n * (n - 1) / 2} = ${sum}.`), S(`n = ${s0}, takže najväčšie číslo je ${s0} + ${n - 1} = ${s0 + n - 1}.`, `n = ${s0}, so the largest is ${s0} + ${n - 1} = ${s0 + n - 1}.`)] }; }
  if (v === 2) { const a = ri(r, 3, sc * 2), b = ri(r, 1, a - 1), sm = a + b, df = a - b; return { title: S('Súčet a rozdiel', 'Sum and difference'), type: 'number', prompt: S(`Súčet dvoch čísel je ${sm} a ich rozdiel je ${df}. Aké je väčšie z nich?`, `The sum of two numbers is ${sm} and their difference is ${df}. What is the bigger one?`), data: { answer: a },
    hints: [S('Keď súčet a rozdiel sčítaš, čo dostaneš?', 'What do you get when you add the sum and the difference?'), S('Dostaneš dvojnásobok väčšieho čísla.', 'You get twice the bigger number.')], explain: [S(`(${sm} + ${df}) = ${sm + df} = 2 · väčšie číslo.`, `(${sm} + ${df}) = ${sm + df} = 2 · the bigger number.`), S(`Väčšie číslo je ${sm + df} : 2 = ${a}.`, `The bigger number is ${sm + df} : 2 = ${a}.`)] }; }
  if (v === 3) { const son = ri(r, 4, 8 + Math.floor(D * 8)), diff = ri(r, 20, 34), sum = 2 * son + diff, ok = son + diff; return { title: S('Vek otca a syna', 'Father and son'), type: 'number', prompt: S(`Otec je o ${diff} rokov starší ako syn. Dokopy majú ${sum} rokov. Koľko rokov má otec?`, `A father is ${diff} years older than his son. Together they are ${sum} years old. How old is the father?`), data: { answer: ok, unit: S('rokov', 'years') },
    hints: [S('Ak by otec mal o tých rokov menej, boli by rovnako starí. Čo by bol súčet?', 'If the father were that many years younger they would be equally old. What would the sum be?'), S('Súčet by sa zmenšil o rozdiel veku.', 'The sum would shrink by the age gap.')], explain: [S(`${sum} − ${diff} = ${sum - diff} = dvojnásobok veku syna.`, `${sum} − ${diff} = ${sum - diff} = twice the son’s age.`), S(`Syn má ${son}, otec ${son} + ${diff} = ${ok}.`, `The son is ${son}, the father ${son} + ${diff} = ${ok}.`)] }; }
  if (v === 4) { const n = ri(r, 8, 14 + Math.floor(D * 10)), y = ri(r, 2, n - 2), val = (n - y) * 1 + y * 2; return { title: S('Mince', 'Coins'), type: 'number', prompt: S(`V pokladničke je ${n} mincí, niektoré po 1 € a ostatné po 2 €. Spolu majú hodnotu ${val} €. Koľko je dvojeurových mincí?`, `A piggy bank holds ${n} coins, some worth €1 and the rest €2. Their total value is €${val}. How many €2 coins are there?`), data: { answer: y },
    hints: [S('Keby všetky mince boli po 1 €, aká by bola hodnota?', 'If all coins were €1, what would the value be?'), S('Každá výmena jednoeurovej za dvojeurovú pridá 1 €.', 'Each swap of a €1 coin for a €2 coin adds €1.')], explain: [S(`Pri ${n} jednoeurových mincách by bolo ${n} €.`, `With ${n} one-euro coins it would be €${n}.`), S(`Chýba ${val - n} €, preto je dvojeurových mincí ${val - n}.`, `€${val - n} is missing, so there are ${val - n} two-euro coins.`)] }; }
  const b = ri(r, 1, 9), x = b + ri(r, 2, lerp(4, 25, D)), a = ri(r, 2, 5), d = ri(r, 1, 9), rhs = a * (x - b) + d; return { title: S('Rovnica so zátvorkou', 'Equation with brackets'), type: 'number', prompt: S(`Vyrieš rovnicu: ${a}·(x − ${b}) + ${d} = ${rhs}. Aké je x?`, `Solve the equation: ${a}·(x − ${b}) + ${d} = ${rhs}. What is x?`), data: { answer: x, work: D > .5 },
    hints: [S('Najprv sa zbav toho, čo je pripočítané mimo zátvorky.', 'First get rid of what is added outside the brackets.'), S(`Po odpočítaní ${d} deľ číslom ${a}.`, `After subtracting ${d}, divide by ${a}.`)], explain: [S(`${rhs} − ${d} = ${rhs - d}, teda ${a}·(x − ${b}) = ${rhs - d}.`, `${rhs} − ${d} = ${rhs - d}, so ${a}·(x − ${b}) = ${rhs - d}.`), S(`x − ${b} = ${(rhs - d) / a}, preto x = ${x}.`, `x − ${b} = ${(rhs - d) / a}, so x = ${x}.`)] };
});

reg('numtheory', 'olymp', 2, c => {
  const { r, D, k } = c, v = k % 6, j = Math.floor(k / 6);
  if (v === 0) { const n = ri(r, 6, lerp(24, 200, D)) + j; let cntD = 0; for (let d = 1; d <= n; d++) if (n % d === 0) cntD++; return { title: S('Deliteľe', 'Divisors'), type: 'number', prompt: S(`Koľko deliteľov (vrátane 1 a samotného čísla) má číslo ${n}?`, `How many divisors (including 1 and the number itself) does ${n} have?`), data: { answer: cntD },
    hints: [S('Hľadaj deliteľe v pároch: ak d delí n, delí ho aj n : d.', 'Look for divisors in pairs: if d divides n then so does n : d.'), S(`Skúšaj d = 1, 2, 3, … až po odmocninu z ${n}.`, `Try d = 1, 2, 3, … up to the square root of ${n}.`)], explain: [S('Deliteľe zapisujeme v pároch (d, n : d).', 'We list divisors in pairs (d, n : d).'), both(l => (l === 'sk' ? 'Sú to: ' : 'They are: ') + range(n).map(i => i + 1).filter(d => n % d === 0).join(', ') + ` (${cntD}).`)] }; }
  if (v === 1) { const a = ri(r, 4, lerp(8, 24, D)), b = ri(r, 3, lerp(7, 20, D)); if (a === b) return null; return { title: S('Dva autobusy', 'Two buses'), type: 'number', prompt: S(`Z námestia odchádza linka A každých ${a} minút a linka B každých ${b} minút. Teraz odišli spolu. Za koľko minút odídu spolu znova?`, `From the square, bus A leaves every ${a} minutes and bus B every ${b} minutes. They have just left together. After how many minutes will they leave together again?`), data: { answer: lcm(a, b), unit: S('minút', 'minutes') },
    hints: [S('Hľadáš číslo, ktoré je násobkom oboch časov.', 'You need a number that is a multiple of both times.'), S('Najmenší spoločný násobok.', 'The least common multiple.')], explain: [S(`Násobky ${a}: ${range(4).map(i => a * (i + 1)).join(', ')} …; násobky ${b}: ${range(4).map(i => b * (i + 1)).join(', ')} …`, `Multiples of ${a}: ${range(4).map(i => a * (i + 1)).join(', ')} …; multiples of ${b}: ${range(4).map(i => b * (i + 1)).join(', ')} …`), S(`Najmenší spoločný násobok je ${lcm(a, b)}.`, `The least common multiple is ${lcm(a, b)}.`)] }; }
  if (v === 2) { const a = ri(r, 2, 9), e = ri(r, 10, 20 + Math.floor(D * 80)) + j; let x = 1; for (let i = 0; i < e; i++) x = x * a % 10; return { title: S('Posledná číslica', 'The last digit'), type: 'number', prompt: S(`Aká je posledná číslica čísla ${a}^${e}?`, `What is the last digit of ${a}^${e}?`), data: { answer: x, work: D > .6 },
    hints: [S(`Vypíš posledné číslice mocnín ${a}¹, ${a}², ${a}³ …`, `Write the last digits of the powers ${a}¹, ${a}², ${a}³ …`), S('Posledné číslice sa opakujú s periódou. Aká je perióda a čo ostane po delení ' + e + '?', 'The last digits repeat with a period. What is it, and what remains after dividing ' + e + '?')], explain: (() => { const seq = []; let y = 1; for (let i = 0; i < 12; i++) { y = y * a % 10; seq.push(y); } let per = 4; for (let p = 1; p <= 4; p++) if (range(8).every(i => seq[i] === seq[i + p])) { per = p; break; } return [S(`Posledné číslice mocnín: ${seq.slice(0, 8).join(', ')} … (perióda ${per}).`, `Last digits of the powers: ${seq.slice(0, 8).join(', ')} … (period ${per}).`), S(`Exponent ${e} dáva po delení ${per} zvyšok ${e % per}, preto je posledná číslica ${x}.`, `Exponent ${e} leaves remainder ${e % per} on division by ${per}, so the last digit is ${x}.`)]; })() }; }
  if (v === 3) { const N = ri(r, 30, lerp(60, 400, D)) + j, a = ri(r, 2, 6), b = ri(r, a + 1, 9); let cn = 0; for (let i = 1; i <= N; i++) if (i % a === 0 || i % b === 0) cn++; return { title: S('Násobky dvoch čísel', 'Multiples of two numbers'), type: 'number', prompt: S(`Koľko čísel od 1 do ${N} je deliteľných číslom ${a} alebo číslom ${b} (alebo oboma)?`, `How many numbers from 1 to ${N} are divisible by ${a} or by ${b} (or both)?`), data: { answer: cn },
    hints: [S('Spočítaj osobitne násobky prvého a druhého čísla.', 'Count the multiples of each number separately.'), S('Čísla deliteľné oboma si započítal dvakrát – odpočítaj ich raz.', 'Numbers divisible by both were counted twice – subtract them once.')], explain: [S(`Násobky ${a}: ${Math.floor(N / a)}, násobky ${b}: ${Math.floor(N / b)}, oboch (${lcm(a, b)}): ${Math.floor(N / lcm(a, b))}.`, `Multiples of ${a}: ${Math.floor(N / a)}, of ${b}: ${Math.floor(N / b)}, of both (${lcm(a, b)}): ${Math.floor(N / lcm(a, b))}.`), S(`${Math.floor(N / a)} + ${Math.floor(N / b)} − ${Math.floor(N / lcm(a, b))} = ${cn}.`, `${Math.floor(N / a)} + ${Math.floor(N / b)} − ${Math.floor(N / lcm(a, b))} = ${cn}.`)] }; }
  if (v === 4) { const n = ri(r, 10, lerp(25, 120, D)) + j; let z = 0, q = 5; while (q <= n) { z += Math.floor(n / q); q *= 5; } return { title: S('Nuly na konci', 'Trailing zeros'), type: 'number', prompt: S(`Na koľko núl končí číslo ${n}! = 1 · 2 · 3 · … · ${n}?`, `How many zeros does ${n}! = 1 · 2 · 3 · … · ${n} end with?`), data: { answer: z, work: D > .6 },
    hints: [S('Nula na konci vzniká z dvojice činiteľov 2 a 5. Čoho je v súčine menej?', 'A trailing zero comes from a pair of factors 2 and 5. Which is rarer in the product?'), S(`Spočítaj, koľkokrát sa činiteľ 5 vyskytuje v číslach od 1 do ${n} (aj viackrát, napr. 25).`, `Count how often the factor 5 occurs in the numbers from 1 to ${n} (also repeatedly, e.g. 25).`)], explain: [S('Dvojok je v súčine oveľa viac než päťok, preto rozhodujú päťky.', 'There are far more twos than fives, so the fives decide.'), S(`Počet päťok: ${[...Array(4)].map((_, i) => Math.floor(n / 5 ** (i + 1))).filter(x => x > 0).join(' + ')} = ${z}.`, `Number of fives: ${[...Array(4)].map((_, i) => Math.floor(n / 5 ** (i + 1))).filter(x => x > 0).join(' + ')} = ${z}.`)] }; }
  const a = ri(r, 12, lerp(30, 240, D)) + j, b = ri(r, 8, lerp(20, 180, D)), g2 = gcd(a, b); if (g2 < 2) return null; return { title: S('Najväčší štvorec', 'The largest square'), type: 'number', prompt: S(`Obdĺžnik ${a} cm × ${b} cm chceme pokryť rovnakými štvorcami bez zvyšku a bez prekrývania. Aká je najväčšia možná strana štvorca (v cm)?`, `We want to cover a ${a} cm × ${b} cm rectangle with identical squares, no gaps and no overlap. What is the largest possible side of a square (in cm)?`), data: { answer: g2, unit: 'cm' },
    hints: [S('Strana štvorca musí deliť oba rozmery.', 'The square’s side must divide both dimensions.'), S('Hľadáš najväčšieho spoločného deliteľa.', 'You need the greatest common divisor.')], explain: [S(`Deliteľe ${a} aj ${b}: spoločné sú ${range(Math.min(a, b)).map(i => i + 1).filter(d => a % d === 0 && b % d === 0).join(', ')}.`, `Common divisors of ${a} and ${b}: ${range(Math.min(a, b)).map(i => i + 1).filter(d => a % d === 0 && b % d === 0).join(', ')}.`), S(`Najväčší je ${g2}.`, `The largest is ${g2}.`)] };
});

reg('prob', 'prob', 5, c => {
  const { r, D, k } = c, v = D < .35 ? k % 2 : D < .7 ? k % 4 : k % 5;
  if (v === 0) { const rd = ri(r, 1, 7), bl = ri(r, 1, 7), gr = ri(r, 0, 4), t = rd + bl + gr; return { title: S('Vytiahnem guľôčku', 'Drawing a marble'), type: 'number', prompt: S(`Vo vrecku je ${rd} červených, ${bl} modrých a ${gr} zelených guľôčok. Vytiahneme jednu poslepiačky. Aká je pravdepodobnosť, že bude červená? (Zlomkom v základnom tvare, napr. 1/6.)`, `A bag holds ${rd} red, ${bl} blue and ${gr} green marbles. One is drawn blindly. What is the probability it is red? (As a fraction in lowest terms, e.g. 1/6.)`), data: { answer: fracStr(rd, t) },
    hints: [S('Pravdepodobnosť = priaznivé : všetky možné.', 'Probability = favourable : all possible.'), S(`Koľko je všetkých guľôčok a koľko priaznivých?`, `How many marbles are there in all, and how many are favourable?`)], explain: [S(`Všetkých guľôčok je ${t}, červených ${rd}.`, `There are ${t} marbles in all, ${rd} are red.`), S(`Pravdepodobnosť je ${rd}/${t} = ${fracStr(rd, t)}.`, `The probability is ${rd}/${t} = ${fracStr(rd, t)}.`)] }; }
  if (v === 1) { const s = ri(r, 2, 12); let n = 0; for (let a = 1; a <= 6; a++) for (let b = 1; b <= 6; b++) if (a + b === s) n++; return { title: S('Dve kocky', 'Two dice'), type: 'number', prompt: S(`Hodíme dvomi pravidelnými kockami. Aká je pravdepodobnosť, že súčet bodov bude ${s}? (Zlomkom v základnom tvare.)`, `We roll two fair dice. What is the probability that the sum is ${s}? (As a fraction in lowest terms.)`), data: { answer: fracStr(n, 36) },
    hints: [S('Koľko všetkých výsledkov hodu dvoch kociek existuje?', 'How many outcomes are there when rolling two dice?'), S(`Vypíš dvojice so súčtom ${s}.`, `List the pairs with sum ${s}.`)], explain: [S('Všetkých výsledkov je 6 · 6 = 36.', 'There are 6 · 6 = 36 outcomes.'), S(`Súčet ${s} dáva ${n} dvojíc, preto ${n}/36 = ${fracStr(n, 36)}.`, `Sum ${s} comes from ${n} pairs, so ${n}/36 = ${fracStr(n, 36)}.`)] }; }
  if (v === 2) { const n = ri(r, 3, 6), kk = ri(r, 1, n - 1); return { title: S('Hody mincou', 'Coin tosses'), type: 'number', prompt: S(`Mincou hodíme ${n}-krát. Aká je pravdepodobnosť, že padne presne ${kk}-krát hlava? (Zlomkom v základnom tvare.)`, `A coin is tossed ${n} times. What is the probability of exactly ${kk} heads? (As a fraction in lowest terms.)`), data: { answer: fracStr(binom(n, kk), 2 ** n) },
    hints: [S(`Koľko všetkých výsledkov je pri ${n} hodoch?`, `How many outcomes are there for ${n} tosses?`), S(`Koľkými spôsobmi vyberieš, ktoré ${kk} z ${n} hodov budú hlavy?`, `In how many ways can you choose which ${kk} of the ${n} tosses are heads?`)], explain: [S(`Všetkých výsledkov: 2^${n} = ${2 ** n}.`, `All outcomes: 2^${n} = ${2 ** n}.`), S(`Priaznivých: C(${n}, ${kk}) = ${binom(n, kk)}. Pravdepodobnosť ${binom(n, kk)}/${2 ** n} = ${fracStr(binom(n, kk), 2 ** n)}.`, `Favourable: C(${n}, ${kk}) = ${binom(n, kk)}. Probability ${binom(n, kk)}/${2 ** n} = ${fracStr(binom(n, kk), 2 ** n)}.`)] }; }
  if (v === 3) { const rd = ri(r, 2, 6), bl = ri(r, 2, 6), t = rd + bl; return { title: S('Dve guľôčky bez vrátenia', 'Two marbles, no replacement'), type: 'number', prompt: S(`Vo vreci je ${rd} červených a ${bl} modrých guľôčok. Vytiahneme dve bez vrátenia. Aká je pravdepodobnosť, že obe budú červené? (Zlomkom v základnom tvare.)`, `A bag holds ${rd} red and ${bl} blue marbles. Two are drawn without replacement. What is the probability that both are red? (As a fraction in lowest terms.)`), data: { answer: fracStr(rd * (rd - 1), t * (t - 1)) },
    hints: [S('Aká je pravdepodobnosť, že prvá je červená?', 'What is the probability that the first is red?'), S('Po vytiahnutí červenej koľko červených a koľko všetkých zostane?', 'After drawing a red one, how many reds and how many marbles remain?')], explain: [S(`Prvá červená: ${rd}/${t}.`, `First red: ${rd}/${t}.`), S(`Druhá červená: ${rd - 1}/${t - 1}. Spolu ${rd}/${t} · ${rd - 1}/${t - 1} = ${fracStr(rd * (rd - 1), t * (t - 1))}.`, `Second red: ${rd - 1}/${t - 1}. Together ${rd}/${t} · ${rd - 1}/${t - 1} = ${fracStr(rd * (rd - 1), t * (t - 1))}.`)] }; }
  const f = ri(r, 1, 6); let n = 0; for (let a = 1; a <= 6; a++) for (let b = 1; b <= 6; b++) if (a === f || b === f) n++; return { title: S('Aspoň jedna šestka… (a spol.)', 'At least one … (and co.)'), type: 'number', prompt: S(`Hodíme dvomi kockami. Aká je pravdepodobnosť, že aspoň na jednej padne ${f}? (Zlomkom v základnom tvare.)`, `We roll two dice. What is the probability that at least one shows ${f}? (As a fraction in lowest terms.)`), data: { answer: fracStr(n, 36) },
    hints: [S(`Jednoduchšie je počítať opak: na žiadnej nepadne ${f}.`, `It is easier to count the opposite: neither shows ${f}.`), S('Odpočítaj opačnú pravdepodobnosť od 1.', 'Subtract the opposite probability from 1.')], explain: [S(`Na žiadnej kocke nepadne ${f}: 5 · 5 = 25 z 36 výsledkov.`, `Neither die shows ${f}: 5 · 5 = 25 of 36 outcomes.`), S(`Priaznivých je 36 − 25 = ${n}, pravdepodobnosť ${fracStr(n, 36)}.`, `Favourable: 36 − 25 = ${n}, probability ${fracStr(n, 36)}.`)] };
});

reg('percent', 'algebra', 4, c => {
  const { r, D, k } = c, v = k % 5, j = Math.floor(k / 5);
  if (v === 0) { const p = pick([10, 20, 25, 30, 40, 50, 5, 15, 60, 75], r), base = ri(r, 2, lerp(10, 90, D)) * 20 + j * 20; return { title: S('Percentá z čísla', 'Percent of a number'), type: 'number', prompt: S(`Koľko je ${p} % z čísla ${base}?`, `What is ${p}% of ${base}?`), data: { answer: base * p / 100 },
    hints: [S('Najprv zisti, koľko je 1 % z celku.', 'First find 1% of the whole.'), S(`1 % z ${base} je ${base / 100}.`, `1% of ${base} is ${base / 100}.`)], explain: [S(`1 % z ${base} je ${base / 100}.`, `1% of ${base} is ${base / 100}.`), S(`${p} % je ${p} · ${base / 100} = ${base * p / 100}.`, `${p}% is ${p} · ${base / 100} = ${base * p / 100}.`)] }; }
  if (v === 1) { const price = ri(r, 4, lerp(12, 80, D)) * 50 + j * 50, up = pick([10, 20, 30, 50], r), down = pick([10, 20, 50], r), mid = price * (100 + up) / 100, fin = mid * (100 - down) / 100; if (!Number.isInteger(fin)) return null; return { title: S('Zdražovanie a zlacnenie', 'Price up, price down'), type: 'number', prompt: S(`Tovar stojí ${price} €. Najprv zdražie o ${up} % a potom nová cena zlacnie o ${down} %. Koľko € stojí nakoniec?`, `An item costs €${price}. First it rises by ${up}%, then the new price falls by ${down}%. What does it cost in the end?`), data: { answer: fin, unit: '€' },
    hints: [S('Percentá počítaj vždy z aktuálnej ceny.', 'Always take the percentage of the current price.'), S('Najprv vypočítaj cenu po zdražení.', 'First compute the price after the rise.')], explain: [S(`Po zdražení: ${price} · ${(100 + up) / 100} = ${mid} €.`, `After the rise: ${price} · ${(100 + up) / 100} = €${mid}.`), S(`Po zlacnení: ${mid} · ${(100 - down) / 100} = ${fin} €.`, `After the fall: ${mid} · ${(100 - down) / 100} = €${fin}.`)] }; }
  if (v === 2) { const a = ri(r, 1, 6), b = ri(r, 1, 6); if (a === b) return null; const tot = (a + b) * ri(r, 3, lerp(8, 60, D)) + j * (a + b); return { title: S('Delenie v pomere', 'Sharing in a ratio'), type: 'number', prompt: S(`${tot} € sa rozdelí medzi Emu a Adama v pomere ${a} : ${b}. Koľko € dostane Ema?`, `€${tot} is shared between Ema and Adam in the ratio ${a} : ${b}. How many € does Ema get?`), data: { answer: tot / (a + b) * a, unit: '€' },
    hints: [S('Koľko dielov je spolu?', 'How many parts are there in total?'), S('Zisti hodnotu jedného dielu.', 'Find the value of one part.')], explain: [S(`Dielov je ${a} + ${b} = ${a + b}, jeden diel je ${tot} : ${a + b} = ${tot / (a + b)} €.`, `There are ${a} + ${b} = ${a + b} parts, one part is ${tot} : ${a + b} = €${tot / (a + b)}.`), S(`Ema dostane ${a} dielov: ${a} · ${tot / (a + b)} = ${tot / (a + b) * a} €.`, `Ema gets ${a} parts: ${a} · ${tot / (a + b)} = €${tot / (a + b) * a}.`)] }; }
  if (v === 3) { const q = ri(r, 2, 6), p = ri(r, 3, 9); if (q >= p) return null; const base = p * ri(r, 2, lerp(6, 40, D)) + j * p; return { title: S('Zlomok z čísla', 'Fraction of a number'), type: 'number', prompt: S(`Koľko je ${q}/${p} z čísla ${base}?`, `What is ${q}/${p} of ${base}?`), data: { answer: base / p * q },
    hints: [S('Najprv vypočítaj jednu časť (1/' + p + ').', 'First find one part (1/' + p + ').'), S('Potom ju vynásob počtom častí.', 'Then multiply by the number of parts.')], explain: [S(`1/${p} z ${base} je ${base} : ${p} = ${base / p}.`, `1/${p} of ${base} is ${base} : ${p} = ${base / p}.`), S(`${q}/${p} je ${q} · ${base / p} = ${base / p * q}.`, `${q}/${p} is ${q} · ${base / p} = ${base / p * q}.`)] }; }
  const whole = pick([20, 25, 40, 50, 80, 120, 200, 250], r) + j * 20, p = pick([10, 20, 25, 30, 40, 50, 60, 75, 80], r); if (!Number.isInteger(whole * p / 100)) return null; const part = whole * p / 100; return { title: S('Koľko percent?', 'What percent?'), type: 'number', prompt: S(`Koľko percent je ${part} z čísla ${whole}?`, `What percent is ${part} of ${whole}?`), data: { answer: p, unit: '%' },
    hints: [S('Utvor zlomok časť / celok.', 'Form the fraction part / whole.'), S('Zlomok prepočítaj na stotiny.', 'Convert the fraction to hundredths.')], explain: [S(`${part} / ${whole} = ${part / whole}.`, `${part} / ${whole} = ${part / whole}.`), S(`To je ${p} stotín, teda ${p} %.`, `That is ${p} hundredths, i.e. ${p}%.`)] };
});

reg('clock', 'algebra', 2, c => {
  const { r, D, k, g } = c, v = g <= 3 ? 0 : D < .3 ? k % 3 : k % 4, j = Math.floor(k / 4);
  if (v === 0) { const d0 = ri(r, 0, 6), n = g <= 3 ? ri(r, 2, 13) + (j % 2) : ri(r, 8, lerp(20, 400, D)) + j * 3, ans = (d0 + n) % 7; const opts = shuffle([ans, ...shuffle(range(7).filter(x => x !== ans), r).slice(0, 3)], r); return { title: S('Aký bude deň?', 'What day will it be?'), type: 'choice', prompt: S(`Dnes je ${DAYS[d0].sk}. Aký deň v týždni bude za ${n} dní?`, `Today is ${DAYS[d0].en}. What day of the week will it be in ${n} days?`), data: { options: opts.map(i => DAYS[i]), correct: opts.indexOf(ans), cols: 2 },
    hints: [S('Týždeň má 7 dní. Čo sa stane po 7 dňoch?', 'A week has 7 days. What happens after 7 days?'), S(`Zisti zvyšok po delení ${n} siedmimi.`, `Find the remainder of ${n} divided by 7.`)], explain: [S(`${n} : 7 = ${Math.floor(n / 7)} zvyšok ${n % 7}.`, `${n} : 7 = ${Math.floor(n / 7)} remainder ${n % 7}.`), S(`Celé týždne nemenia deň; posunieme sa o ${n % 7} dní dopredu od dňa „${DAYS[d0].sk}“ a dostaneme „${DAYS[ans].sk}“.`, `Whole weeks do not change the day; move ${n % 7} days forward from ${DAYS[d0].en} to get ${DAYS[ans].en}.`)] }; }
  if (v === 1) { const h0 = ri(r, 5, 18), m0 = ri(r, 0, 11) * 5, dur = ri(r, 35, lerp(120, 330, D)) + j; const end = h0 * 60 + m0 + dur, fmt = x => `${Math.floor(x / 60) % 24}:${String(x % 60).padStart(2, '0')}`; return { title: S('Cestovný poriadok', 'Timetable'), type: 'number', prompt: S(`Vlak odchádza o ${fmt(h0 * 60 + m0)} a prichádza o ${fmt(end)}. Koľko minút trvá cesta?`, `A train leaves at ${fmt(h0 * 60 + m0)} and arrives at ${fmt(end)}. How many minutes does the journey take?`), data: { answer: dur, unit: S('minút', 'minutes') },
    hints: [S('Prepočítaj hodiny na minúty alebo dopočítaj do celej hodiny.', 'Convert hours to minutes or count up to a full hour.'), S('Najprv do najbližšej celej hodiny, potom celé hodiny, nakoniec zvyšné minúty.', 'First up to the next full hour, then whole hours, then the leftover minutes.')], explain: [S(`${fmt(h0 * 60 + m0)} = ${h0 * 60 + m0} minút od polnoci, ${fmt(end)} = ${end} minút.`, `${fmt(h0 * 60 + m0)} = ${h0 * 60 + m0} minutes after midnight, ${fmt(end)} = ${end} minutes.`), S(`Rozdiel je ${dur} minút.`, `The difference is ${dur} minutes.`)] }; }
  if (v === 2) { const d0 = ri(r, 0, 6), mo = ri(r, 0, 10), yr = 2025 + ri(r, 0, 3), dd = ri(r, 3, 25) + j % 3, base = new Date(yr, mo, 1), tgt = new Date(yr, mo + 1, 1); const wd = x => (x.getDay() + 6) % 7, dif = Math.round((tgt - base) / 864e5), d1 = wd(base), ans = wd(tgt); const mon = [S('januára', 'January'), S('februára', 'February'), S('marca', 'March'), S('apríla', 'April'), S('mája', 'May'), S('júna', 'June'), S('júla', 'July'), S('augusta', 'August'), S('septembra', 'September'), S('októbra', 'October'), S('novembra', 'November'), S('decembra', 'December')]; const nom = [S('január', 'January'), S('február', 'February'), S('marec', 'March'), S('apríl', 'April'), S('máj', 'May'), S('jún', 'June'), S('júl', 'July'), S('august', 'August'), S('september', 'September'), S('október', 'October'), S('november', 'November'), S('december', 'December')];
    const opts = shuffle([ans, ...shuffle(range(7).filter(x => x !== ans), r).slice(0, 3)], r); return { title: S('Kalendár', 'Calendar'), type: 'choice', prompt: S(`V roku ${yr} pripadne 1. ${mon[mo].sk} na ${DAYS_ACC[d1]}. Aký deň v týždni bude 1. ${mon[(mo + 1) % 12].sk}?`, `In ${yr}, 1 ${mon[mo].en} falls on a ${DAYS[d1].en}. What day of the week is 1 ${mon[(mo + 1) % 12].en}?`), data: { options: opts.map(i => DAYS[i]), correct: opts.indexOf(ans), cols: 2 },
      hints: [S('Koľko dní má ten mesiac? Zisti zvyšok po delení 7.', 'How many days does that month have? Find the remainder on dividing by 7.'), S('O toľko dní sa deň v týždni posunie.', 'The weekday shifts by that many days.')], explain: [S(`Mesiac má ${dif} dní: ${dif} : 7 = ${Math.floor(dif / 7)} zvyšok ${dif % 7}.`, `The month has ${dif} days: ${dif} : 7 = ${Math.floor(dif / 7)} remainder ${dif % 7}.`), S(`Posun o ${dif % 7} dní dopredu od dňa „${DAYS[d1].sk}“ dáva deň „${DAYS[ans].sk}“.`, `Shifting ${dif % 7} days forward from ${DAYS[d1].en} gives ${DAYS[ans].en}.`)] }; }
  const h12 = ri(r, 1, 11), m0 = ri(r, 0, 29) * 2, a = Math.abs(30 * h12 + .5 * m0 - 6 * m0), ang = a > 180 ? 360 - a : a; if (!Number.isInteger(ang)) return null; return { title: S('Uhol ručičiek', 'Angle between hands'), type: 'number', prompt: S(`Aký menší uhol (v stupňoch) zvierajú ručičky hodín o ${h12}:${String(m0).padStart(2, '0')}?`, `What is the smaller angle (in degrees) between the clock hands at ${h12}:${String(m0).padStart(2, '0')}?`), data: { answer: ang, unit: '°', work: D > .6 },
    hints: [S('Minútová ručička prejde za minútu 6°, hodinová za minútu 0,5°.', 'The minute hand moves 6° per minute, the hour hand 0.5° per minute.'), S('Vypočítaj, kde je každá ručička od čísla 12, a odpočítaj.', 'Work out where each hand is measured from 12 and subtract.')], explain: [S(`Hodinová: ${h12} · 30 + ${m0} · 0,5 = ${30 * h12 + .5 * m0}°. Minútová: ${m0} · 6 = ${6 * m0}°.`, `Hour hand: ${h12} · 30 + ${m0} · 0.5 = ${30 * h12 + .5 * m0}°. Minute hand: ${m0} · 6 = ${6 * m0}°.`), S(`Rozdiel ${a}°${a > 180 ? `, menší uhol je 360° − ${a}° = ${ang}°` : ''}. Odpoveď ${ang}°.`, `Difference ${a}°${a > 180 ? `, the smaller angle is 360° − ${a}° = ${ang}°` : ''}. Answer ${ang}°.`)] };
});

/* ---------- interactive & search puzzles ---------- */
const sudokuPrompt = n => S(`🔢 Doplň čísla 1–${n}. V riadku, stĺpci ${n > 3 ? 'ani v rámčeku ' : ''}sa číslo nesmie opakovať.`, `🔢 Fill in the numbers 1–${n}. No repeats in a row, column${n > 3 ? ' or box' : ''}.`);
reg('sudoku', 'sudoku', 2, c => {
  const { r, D, g } = c, n = g <= 2 ? 4 : g <= 4 ? (D < .3 ? 4 : 6) : g <= 6 ? 6 : 9, ds = n === 4 ? [6, 10] : n === 6 ? [14, 24] : [34, 50];
  return { title: S(`Sudoku ${n}×${n}`, `Sudoku ${n}×${n}`), type: 'sudoku', pts: 15, prompt: sudokuPrompt(n), data: { n, holes: lerp(ds[0], ds[1], clamp((D - (g <= 2 ? 0 : .1)) * 1.3, 0, 1)), level: clamp(Math.floor(n === 9 ? (D - .6) / .4 * 6 : n === 6 ? (D - .3) / .3 * 6 : D / .35 * 6), 0, 5), seed: Math.floor(r() * 1e9) },
    hints: [S('Začni tam, kde v riadku, stĺpci alebo štvorčeku chýba najmenej čísel.', 'Start where a row, column or box is missing the fewest numbers.'), 'dyn', 'dyn'], explain: [S('V každom riadku, stĺpci a štvorčeku sa číslo opakovať nesmie.', 'No number may repeat in any row, column or box.')] };
});
reg('lights', 'toggle', 2, c => {
  const { r, D } = c, size = D < .45 ? 3 : 4;
  return { title: S('Zhasni všetky svetlá', 'Switch all lights off'), type: 'lights', pts: 15, prompt: S('💡 Ťuk prepne políčko aj jeho susedov. Zhasni všetky svetlá (○).', '💡 A tap flips the cell and its neighbours. Turn all lights off (○).'), data: { size, presses: size === 3 ? ri(r, 2, 5) : ri(r, 4, lerp(6, 10, D)), seed: Math.floor(r() * 1e9) },
    hints: [S('Skús jedno políčko stlačiť dvakrát. Čo sa stane?', 'Try pressing one cell twice. What happens?'), 'dyn', 'dyn'], explain: [] };
});
function mazeRows(w, hh, r, extra) {
  const R = 2 * hh + 1, C = 2 * w + 1, g = range(R).map(() => Array(C).fill('#')), stack = [[1, 1]]; g[1][1] = '.';
  while (stack.length) { const [a, b] = stack[stack.length - 1], nb = shuffle([[a - 2, b], [a + 2, b], [a, b - 2], [a, b + 2]], r).filter(([x, y]) => x > 0 && y > 0 && x < R - 1 && y < C - 1 && g[x][y] === '#'); if (!nb.length) { stack.pop(); continue; } const [x, y] = nb[0]; g[(a + x) / 2][(b + y) / 2] = '.'; g[x][y] = '.'; stack.push([x, y]); }
  for (let t = 0; t < extra; t++) { const a = ri(r, 1, R - 2), b = ri(r, 1, C - 2); if ((a % 2) !== (b % 2)) g[a][b] = '.'; }
  g[1][1] = 'S'; g[R - 2][C - 2] = 'E'; return g.map(rw => rw.join(''));
}
reg('maze', 'maze', 2, c => {
  const { r, D } = c, w = clamp(lerp(3, 6, D), 3, 6), hh = w;
  return { title: S('Najkratšia cesta', 'The shortest route'), type: 'maze', pts: 15, prompt: S('🚀 Nakresli prstom najkratšiu cestu do 🏁. Cez steny sa nedá.', '🚀 Draw the shortest path to 🏁 with your finger. No crossing walls.'), data: { rows: mazeRows(w, hh, r, lerp(0, 8, D)) },
    hints: [S('Ktoré chodby sú slepé uličky?', 'Which corridors are dead ends?'), 'dyn', 'dyn'], explain: [] };
});

function bridgeSolve(times) {
  const n = times.length, full = (1 << n) - 1, key = (m, s) => m * 2 + s, dist = new Map([[key(full, 0), 0]]), prev = new Map(), done = new Set();
  for (;;) {
    let bk = null, bd = Infinity; for (const [kk, d] of dist) if (!done.has(kk) && d < bd) { bd = d; bk = kk; } if (bk == null) return null; done.add(bk);
    const m = bk >> 1, s = bk & 1; if (m === 0 && s === 1) { const path = []; let cur = bk; while (prev.has(cur)) { const p = prev.get(cur); path.unshift(p); cur = p.from; } return { time: bd, path }; }
    const side = s === 0 ? range(n).filter(i => m >> i & 1) : range(n).filter(i => !(m >> i & 1));
    for (let a = 0; a < side.length; a++) for (let b = a; b < side.length; b++) {
      const who = a === b ? [side[a]] : [side[a], side[b]], t = Math.max(...who.map(i => times[i])); let nm = m; who.forEach(i => nm = s === 0 ? nm & ~(1 << i) : nm | (1 << i));
      const nk = key(nm, 1 - s), nd = bd + t; if (!done.has(nk) && (!dist.has(nk) || nd < dist.get(nk))) { dist.set(nk, nd); prev.set(nk, { from: bk, who, t, dir: s === 0 ? 'over' : 'back' }); }
    }
  }
}
reg('bridge', 'logic', 2, c => {
  const { r, D } = c, n = D < .55 ? 4 : 5, pool = shuffle(range(14).map(i => i + 1), r).slice(0, n).sort((a, b) => a - b), res = bridgeSolve(pool);
  return { title: S('Most v noci', 'Bridge at night'), type: 'number', prompt: S(`${n} turistov musí v noci prejsť cez úzky most. Most uvezie najviac dvoch naraz a majú iba jednu baterku, ktorú musí niekto vždy niesť. Pri prechode dvoch ide tempom pomalšieho. Jednotlivo prejdú za ${pool.join(', ')} minút. Aký najkratší čas (v minútach) na prechod všetkých existuje?`, `${n} hikers must cross a narrow bridge at night. The bridge holds at most two at a time and they have just one torch that someone must always carry. A pair moves at the slower one’s pace. Alone they take ${pool.join(', ')} minutes. What is the shortest total time (in minutes) for everyone to cross?`), data: { answer: res.time, unit: S('minút', 'minutes') },
    hints: [S('Baterku treba vždy niekomu vrátiť. Kto by ju mal vracať?', 'The torch must always be brought back. Who should carry it back?'), S('Dvaja najpomalší by mali ísť spolu – aby sa ich čas nezapočítal dvakrát.', 'The two slowest should cross together so that their time is not counted twice.')],
    explain: [S('Skúšame všetky postupy (počítač ich prehľadá) a hľadáme najkratší:', 'We try all plans (a computer searched them) and look for the shortest:'), both(l => res.path.map((p, i) => `${i + 1}. ${p.who.map(x => pool[x]).join(' + ')} ${p.dir === 'over' ? (l === 'sk' ? 'prejdú' : 'cross') : (l === 'sk' ? 'sa vracia' : 'returns')} (${p.t})`).join(' • ')), S(`Celkový čas je ${res.time} minút.`, `The total time is ${res.time} minutes.`)] };
});

reg('jugs', 'logic', 2, c => {
  const { r, D } = c, mx = lerp(5, 13, D);
  for (let tries = 0; tries < 200; tries++) {
    const a = ri(r, 3, mx), b = ri(r, 2, mx); if (a === b || gcd(a, b) !== 1) continue; const t = ri(r, 1, Math.max(a, b) - 1); if (t === a || t === b) continue;
    const key = (x, y) => x * 100 + y, prev = new Map([[key(0, 0), null]]), q = [[0, 0]]; let found = null;
    while (q.length && !found) { const [x, y] = q.shift(); if (x === t || y === t) { found = [x, y]; break; } const nx = [[a, y, S('naplníme veľký džbán', '')], [x, b, null], [0, y, null], [x, 0, null], [Math.max(0, x - (b - y)), Math.min(b, y + x), null], [Math.min(a, x + y), Math.max(0, y - (a - x)), null]];
      nx.forEach(([p, qq]) => { const kk = key(p, qq); if (!prev.has(kk)) { prev.set(kk, [x, y]); q.push([p, qq]); } }); }
    if (!found) continue; const path = []; let cur = found; while (cur) { path.unshift(cur); cur = prev.get(key(...cur)); } const steps = path.length - 1; if (steps < 3 || steps > lerp(6, 14, D)) continue;
    return { title: S('Džbány na vodu', 'Water jugs'), type: 'number', prompt: S(`Máš dva džbány bez delenia: ${a} l a ${b} l, a dostatok vody. Krok je: džbán úplne naplniť, úplne vyliať, alebo prelievať z jedného do druhého, kým sa zdrojový nevyprázdni alebo cieľový nenaplní. Najmenej koľko krokov potrebuješ, aby si v niektorom džbáne mal presne ${t} l?`, `You have two jugs without markings: ${a} L and ${b} L, and plenty of water. A step is: fill a jug completely, empty a jug completely, or pour from one into the other until the source is empty or the target is full. What is the fewest steps needed to have exactly ${t} L in one of the jugs?`), data: { answer: steps },
      hints: [S('Zapisuj si stav ako dvojicu (obsah prvého, obsah druhého) a skúšaj možné kroky.', 'Write the state as a pair (first jug, second jug) and try the possible steps.'), S('Skús začať naplnením väčšieho džbána a prelievať do menšieho.', 'Try starting by filling the bigger jug and pouring into the smaller.')],
      explain: [S('Stavy (prvý, druhý džbán), ktoré tvoria najkratšiu cestu:', 'States (first, second jug) that form the shortest route:'), { text: S(`${path.map(p => `(${p[0]}, ${p[1]})`).join(' → ')}`, `${path.map(p => `(${p[0]}, ${p[1]})`).join(' → ')}`) }, S(`Je to ${steps} krokov a menej sa nedá (prehľadali sme všetky možnosti).`, `That is ${steps} steps and fewer is impossible (all options were searched).`)] };
  }
  return null;
});

reg('weighing', 'weights', 2, c => {
  const { D, k } = c, n = 3 + k * 2 + Math.floor(D * 25) + ri(c.r, 0, 2), w = (() => { let x = 0, p = 1; while (p < n) { p *= 3; x++; } return x; })();
  return { title: S('Falošná minca', 'The fake coin'), type: 'number', prompt: S(`Medzi ${n} mincami je jedna falošná – je ľahšia než ostatné. Máš rovnoramenné váhy bez závaží. Koľko vážení najmenej stačí na to, aby si falošnú mincu určite našiel?`, `Among ${n} coins one is fake – it is lighter than the rest. You have a balance scale without weights. What is the fewest weighings that surely find the fake?`), data: { answer: w },
    hints: [S('Čo ak mince rozdelíš na tri kôpky? Čo ti povie jedno vážení dvoch kôpok?', 'What if you split the coins into three piles? What does one weighing of two piles tell you?'), S('Každé vážení má 3 výsledky (ľavá ľahšia, pravá ľahšia, rovnováha), preto vie rozlíšiť 3 možnosti.', 'Each weighing has 3 outcomes (left lighter, right lighter, balance), so it can tell 3 options apart.')],
    explain: [S('Jedno vážení rozdelí možnosti na tretiny: porovnáme dve kôpky, tretia ostáva bokom.', 'One weighing splits the options into thirds: compare two piles, the third stays aside.'), S(`Po ${w} váženiach rozlíšime až 3^${w} = ${3 ** w} mincí, čo je aspoň ${n}; po ${w - 1} váženiach iba ${3 ** (w - 1)}. Treba ${w}.`, `After ${w} weighings we can tell apart up to 3^${w} = ${3 ** w} coins, which is at least ${n}; after ${w - 1} weighings only ${3 ** (w - 1)}. We need ${w}.`)] };
});
