'use strict';
/* LogiQ – UI strings (task content lives in content.js as {sk,en}) */
const I18N = {
  sk: {
    subtitle: 'matematické výzvy', language: 'Jazyk', starsPoints: 'Hviezdy a body',
    chessMarked: 'Označené', chessIllegal: 'Takto sa táto figúrka hýbať nemôže. Prečítaj si pravidlá pohybu.', hanoiPeg: 'Tyč', hanoiMin: 'Najmenej', hanoiEmpty: 'Na tejto tyči nie je žiadny disk.', hanoiBig: 'Väčší disk sa nesmie položiť na menší.', hanoiHintMsg: 'Skús presunúť disk {d} z tyče {a} na tyč {b}.', hanoiAuto: 'Ukáž riešenie', gamesTitle: 'Samostatné hry', hanoiGame: 'Hanojské veže', hanoiLead: 'Presuň celú vežu na tretiu tyč. Ťukni na tyč (zdroj) a potom na tyč (cieľ).', hanoiDiscs: 'Počet diskov', hanoiBest: 'Tvoj rekord', hanoiDone: 'Veža je presunutá!', playAgain: 'Hrať znova', openGame: 'Hrať',
    rank: 'Hodnosť', pointsToGo: 'Do hodnosti {r} ti ešte chýba: {n} b.', maxRank: 'Dosiahol si najvyššiu hodnosť. Si legenda!', rankUp: 'Nová hodnosť!', newReward: 'Nová odmena!', dailyBonus: 'Denný bonus', levelBonus: '🏆 Bonus za level', rewardsTitle: 'Odmeny', rewardsLead: 'Za body, hviezdy, sériu dní a vyriešené úlohy odomykáš spoločníkov a farebné témy. Hodnosť získaš za body a nikdy ju nestratíš.', avatarTitle: 'Spoločník', themeTitle: 'Farebná téma', rewardUse: 'Použiť', rewardInUse: 'Používaš', badgesTitle: 'Odznaky', req_points: 'Získaj bodov: {n}', req_stars: 'Získaj hviezd: {n}', req_streak: 'Séria dní: {n}', req_tasks: 'Vyrieš úloh: {n}',
    trainSets: 'Tréningové sady (nekonečne veľa úloh)', trainLead: 'Každé ťuknutie vytvorí novú úlohu daného typu pre tvoj ročník. Body sa tu nepočítajú – je to voľný tréning.', trainNote: 'Tréning – body sa nepočítajú.', handmade: 'Ručne vytvorené úlohy', nimPile: 'Kopa', nimToken: 'žetón', nimTake: 'Vziať {n}', nimTakeFrom: 'Vziať {n} z {p}. kopy', nimPickHint: 'Ťukni na žetón – vezmeš ho aj všetky žetóny napravo.', nimYourTurn: 'Si na ťahu.', nimCpuTurn: 'Počítač premýšľa…', nimYouTook: 'Ty:', nimCpuTook: 'Počítač:',
    nav_home: 'Domov', nav_map: 'Mapa', nav_daily: 'Denná výzva', nav_collection: 'Zbierka', nav_badges: 'Úspechy', nav_profile: 'Profil',
    welcomeLead: 'Objavuj hlavolamy, logiku a stratégiu vo svojom tempe. Za chyby sa tu nikto netrestá – každý pokus ťa posúva ďalej.',
    yourName: 'Tvoje meno (nepovinné)', namePh: 'Ako ťa máme volať?', pickGrade: 'Vyber si ročník', letsGo: 'Začíname',
    gradeChangeLater: 'Ročník môžeš neskôr zmeniť v profile.', noAccount: 'Bez registrácie, bez reklám. Postup sa ukladá iba v tomto zariadení.',
    hello: 'Ahoj, {n}!', helloAnon: 'Ahoj, objaviteľ!', heroNext: 'Čaká ťa svet „{w}“ – level „{l}“.', heroAllDone: 'Zvládol si všetky levely v tomto ročníku! Vyskúšaj výzvy alebo zbierku úloh.',
    start: 'Začať', continue: 'Pokračovať', browseCollection: 'Otvoriť zbierku', stars: 'hviezdy', points: 'body', streakDays: 'dní po sebe', tasksSolved: 'vyriešených úloh',
    yourProgress: 'Tvoj postup', levelsDone: '{a} z {b} levelov hotových', openMap: 'Otvoriť mapu', playDaily: 'Riešiť dnes', seeDaily: 'Zobraziť', dailyDone: 'Dnešná výzva je hotová!',
    recommended: 'Odporúčame', go: 'Prejsť', strongAreas: 'Silné oblasti',
    recNext: 'Pokračuj levelom „{n}“.', recStart: 'Začni levelom „{n}“.', recPractice: 'Precvičuj kategóriu „{c}“ – tu sa dá získať viac hviezd.', recNew: 'Vyskúšaj niečo nové: „{c}“.', recStrong: 'Kategória „{c}“ ti ide výborne – skús náročnejšie úlohy!', recNone: 'Vyrieš pár úloh a ponúkneme ti odporúčania.', recChallenge: 'Zvládol si ročník! Skús výzvy zo svetov vyššieho ročníka.',
    mapLead: 'Svety a levely', finishPrev: 'Najprv dokonči predchádzajúci level.', locked: 'Uzamknuté', challengeWorlds: 'Výzvy pre odvážnych', challengeLead: 'Náročnejšie svety z vyššieho ročníka – vždy odomknuté, ak si chceš zamerať.',
    levelIntro: 'Level obsahuje {n} úloh. Môžeš ich riešiť v ľubovoľnom poradí.', whatWaits: 'Čo ťa čaká', rewards: 'Odmeny', rewStars: 'až {n} hviezd', rewPoints: 'až {n} bodov', rewBadge: 'odznaky za objavy', rewMap: 'ďalšie levely na mape', topics: 'Témy', noPenalty: 'Chyby sa netrestajú. Hviezdy závisia len od použitých nápovied a počtu pokusov.', startLevel: 'Začať level',
    back: 'Späť', challenge: 'Výzva', difficulty: 'Obtiažnosť', hint: 'Nápoveda', explain: 'Vysvetli riešenie', check: 'Skontrolovať', next: 'Ďalšia úloha', done: 'Hotovo', finishLevel: 'Dokončiť level', noMoreHints: 'Žiadne ďalšie nápovedy',
    pickFirst: 'Najprv vyber odpoveď.', typeFirst: 'Najprv zadaj odpoveď.', yourAnswer: 'Tvoja odpoveď', erase: 'Zmazať', workLabel: 'Postup riešenia', workPh: 'Sem napíš, ako si postupoval/a…', pickCell: 'Najprv ťukni na prázdne políčko.', sudFill: 'Ešte zostali prázdne políčka.', row: 'riadok', col: 'stĺpec',
    moveUp: 'Posunúť vyššie', moveDown: 'Posunúť nižšie', restart: 'Začať odznova', moves: 'Ťahy', steps: 'Kroky', undo: 'Vrátiť ťah', sail: 'Preplávať', boatFull: 'Loďka je plná. Ťukni na niekoho v loďke, aby vystúpil.', needRower: 'Na loďke musí byť niekto, kto bude veslovať.', leftBank: 'Ľavý breh', rightBank: 'Pravý breh', onBoat: 'na loďke', ferryUndoNote: 'Vrátime ťah späť…',
    pointsLower: 'bodov', usedHints: 'Použité nápovedy: {n}.', noHintsUsed: 'Bez nápovedy – skvelé!', newBadges: 'Nový odznak!', tryAgain: 'Skúsiť znova', mistakeOk: 'Chyba nie je problém – je to súčasť objavovania.',
    explainAsk: 'Chceš vidieť postup?', explainConfirm: 'Najprv sa môžeš ešte pokúsiť sám/sama alebo použiť nápovedu. Ak si zobrazíš riešenie, úloha sa započíta bez bodov.', keepTrying: 'Ešte skúsim', showSolution: 'Ukáž postup', explainedToast: 'Úloha je označená ako preskúmaná. Ideme ďalej!',
    explainIntro: 'Skúsme sa pozrieť, prečo toto funguje.', nextStep: 'Ďalší krok', showAll: 'Zobraziť všetko', close: 'Zavrieť', correctAnswer: 'Správna odpoveď',
    levelDoneTitle: 'Level dokončený!', motivation: 'Každá úloha ti trénuje myseľ. Si čoraz lepší/a – len tak ďalej!', whatNext: 'Čo skúsiť ďalej', nextLevel: 'Ďalší level',
    todayChallenge: 'Dnešná výzva', dailyLead: 'Jedna úloha každý deň. Postupne si budujeme sériu.', dailyDoneLong: 'Dnešnú výzvu máš za sebou. Vráť sa zajtra!', comeBack: 'Zajtra bude nová.', replay: 'Skúsiť znova', streak: 'Séria', notYet: 'ešte nie', streakLead: 'Séria rastie, keď vyriešiš aspoň jednu úlohu každý deň.',
    collectionLead: 'Všetky úlohy ({n}) na voľné precvičovanie. Vyskúšať môžeš aj náročnejšie ročníky.', all: 'Všetky', category: 'Kategória', gradeBand: 'Ročník', randomTask: 'Náhodná úloha', new: 'nové',
    badgesLead: 'Získané odznaky: {a} z {b}', earned: 'získané',
    yourProfile: 'Tvoj profil', anon: 'Žiak', gradeChangeNote: 'Po zmene ročníka sa zmení mapa levelov. Doterajšie hviezdy ti zostávajú.', settings: 'Nastavenia', sounds: 'Zvuky', animations: 'Animácie', bigText: 'Väčšie písmo', saved: 'Uložené',
    history: 'História', noHistory: 'Zatiaľ nič – vyrieš prvú úlohu!', adminTitle: 'Pre učiteľov a autorov: databáza úloh', adminLead: 'Prehľad všetkých úloh vrátane zdroja inšpirácie a licencie. Nové úlohy sa pridávajú do súboru js/content.js.', exportDb: 'Exportovať databázu (JSON)', taskType: 'Typ', source: 'Zdroj', license: 'Licencia',
    syncNote: 'Architektúra je pripravená na budúce prihlásenie a synchronizáciu (výmenný úložný adaptér).', dataTitle: 'Údaje', dataLead: 'Postup sa ukladá iba v tomto zariadení.', resetProgress: 'Vymazať postup', resetConfirm: 'Naozaj chceš vymazať hviezdy, body a odznaky? Meno, ročník a nastavenia zostanú.', cancel: 'Zrušiť', yesReset: 'Áno, vymazať', resetDone: 'Postup bol vymazaný.'
  },
  en: {
    subtitle: 'maths challenges', language: 'Language', starsPoints: 'Stars and points',
    chessMarked: 'Marked', chessIllegal: 'This piece cannot move like that. Read the movement rules.', hanoiPeg: 'Peg', hanoiMin: 'Fewest', hanoiEmpty: 'There is no disc on this peg.', hanoiBig: 'A larger disc may not be placed on a smaller one.', hanoiHintMsg: 'Try moving disc {d} from peg {a} to peg {b}.', hanoiAuto: 'Show the solution', gamesTitle: 'Stand-alone games', hanoiGame: 'Tower of Hanoi', hanoiLead: 'Move the whole tower to the third peg. Tap a peg (source), then a peg (target).', hanoiDiscs: 'Number of discs', hanoiBest: 'Your record', hanoiDone: 'The tower is moved!', playAgain: 'Play again', openGame: 'Play',
    rank: 'Rank', pointsToGo: 'To reach {r} you still need: {n} pts.', maxRank: 'You reached the highest rank. You are a legend!', rankUp: 'New rank!', newReward: 'New reward!', dailyBonus: 'Daily bonus', levelBonus: '🏆 Level bonus', rewardsTitle: 'Rewards', rewardsLead: 'Points, stars, day streaks and solved tasks unlock companions and colour themes. Your rank comes from points and is never lost.', avatarTitle: 'Companion', themeTitle: 'Colour theme', rewardUse: 'Use', rewardInUse: 'In use', badgesTitle: 'Badges', req_points: 'Earn {n} points', req_stars: 'Earn {n} stars', req_streak: '{n}-day streak', req_tasks: 'Solve {n} tasks',
    trainSets: 'Training sets (endless tasks)', trainLead: 'Every tap creates a fresh task of that type for your grade. No points here – it is free practice.', trainNote: 'Practice – no points counted.', handmade: 'Hand-made tasks', nimPile: 'Pile', nimToken: 'token', nimTake: 'Take {n}', nimTakeFrom: 'Take {n} from pile {p}', nimPickHint: 'Tap a token – you take it and all tokens to its right.', nimYourTurn: 'Your turn.', nimCpuTurn: 'The computer is thinking…', nimYouTook: 'You:', nimCpuTook: 'Computer:',
    nav_home: 'Home', nav_map: 'Map', nav_daily: 'Daily', nav_collection: 'Collection', nav_badges: 'Awards', nav_profile: 'Profile',
    welcomeLead: 'Discover puzzles, logic and strategy at your own pace. Nobody is punished for mistakes here – every attempt moves you forward.',
    yourName: 'Your name (optional)', namePh: 'What should we call you?', pickGrade: 'Choose your grade', letsGo: 'Let’s go',
    gradeChangeLater: 'You can change your grade later in your profile.', noAccount: 'No sign-up, no ads. Progress is saved only on this device.',
    hello: 'Hi, {n}!', helloAnon: 'Hi, explorer!', heroNext: 'World “{w}” awaits – level “{l}”.', heroAllDone: 'You finished every level of this grade! Try the challenges or the collection.',
    start: 'Start', continue: 'Continue', browseCollection: 'Open collection', stars: 'stars', points: 'points', streakDays: 'days in a row', tasksSolved: 'tasks solved',
    yourProgress: 'Your progress', levelsDone: '{a} of {b} levels done', openMap: 'Open map', playDaily: 'Solve today’s', seeDaily: 'View', dailyDone: 'Today’s challenge is done!',
    recommended: 'We suggest', go: 'Go', strongAreas: 'Strong areas',
    recNext: 'Continue with level “{n}”.', recStart: 'Start with level “{n}”.', recPractice: 'Practise “{c}” – more stars to earn there.', recNew: 'Try something new: “{c}”.', recStrong: '“{c}” is going great – try harder tasks!', recNone: 'Solve a few tasks and we will offer suggestions.', recChallenge: 'You finished the grade! Try challenges from higher-grade worlds.',
    mapLead: 'Worlds and levels', finishPrev: 'Finish the previous level first.', locked: 'Locked', challengeWorlds: 'Challenges for the bold', challengeLead: 'Harder worlds from a higher grade – always unlocked if you want to stretch yourself.',
    levelIntro: 'This level has {n} tasks. Solve them in any order.', whatWaits: 'What awaits you', rewards: 'Rewards', rewStars: 'up to {n} stars', rewPoints: 'up to {n} points', rewBadge: 'badges for discoveries', rewMap: 'more levels on the map', topics: 'Topics', noPenalty: 'Mistakes are never punished. Stars depend only on hints used and number of attempts.', startLevel: 'Start level',
    back: 'Back', challenge: 'Challenge', difficulty: 'Difficulty', hint: 'Hint', explain: 'Explain solution', check: 'Check', next: 'Next task', done: 'Done', finishLevel: 'Finish level', noMoreHints: 'No more hints',
    pickFirst: 'Pick an answer first.', typeFirst: 'Type an answer first.', yourAnswer: 'Your answer', erase: 'Erase', workLabel: 'Your working', workPh: 'Write how you worked it out…', pickCell: 'Tap an empty cell first.', sudFill: 'Some cells are still empty.', row: 'row', col: 'column',
    moveUp: 'Move up', moveDown: 'Move down', restart: 'Start over', moves: 'Moves', steps: 'Steps', undo: 'Undo move', sail: 'Sail', boatFull: 'The boat is full. Tap someone on the boat to let them off.', needRower: 'Someone must be on the boat to row it.', leftBank: 'Left bank', rightBank: 'Right bank', onBoat: 'on the boat', ferryUndoNote: 'Let us undo that move…',
    pointsLower: 'points', usedHints: 'Hints used: {n}.', noHintsUsed: 'No hints used – great!', newBadges: 'New badge!', tryAgain: 'Try again', mistakeOk: 'A mistake is fine – it is part of discovering.',
    explainAsk: 'Want to see the method?', explainConfirm: 'You can still try on your own or use a hint first. If you reveal the solution, the task counts without points.', keepTrying: 'I’ll keep trying', showSolution: 'Show the method', explainedToast: 'Task marked as explored. Let us move on!',
    explainIntro: 'Let us look at why this works.', nextStep: 'Next step', showAll: 'Show all', close: 'Close', correctAnswer: 'Correct answer',
    levelDoneTitle: 'Level complete!', motivation: 'Every task trains your mind. You keep getting better – keep going!', whatNext: 'What to try next', nextLevel: 'Next level',
    todayChallenge: 'Today’s challenge', dailyLead: 'One task a day. Step by step we build a streak.', dailyDoneLong: 'You have finished today’s challenge. Come back tomorrow!', comeBack: 'A new one tomorrow.', replay: 'Play again', streak: 'Streak', notYet: 'not yet', streakLead: 'Your streak grows when you solve at least one task each day.',
    collectionLead: 'All tasks ({n}) for free practice. You may try harder grades too.', all: 'All', category: 'Category', gradeBand: 'Grade', randomTask: 'Random task', new: 'new',
    badgesLead: 'Badges earned: {a} of {b}', earned: 'earned',
    yourProfile: 'Your profile', anon: 'Student', gradeChangeNote: 'Changing grade changes the level map. Your stars stay.', settings: 'Settings', sounds: 'Sounds', animations: 'Animations', bigText: 'Larger text', saved: 'Saved',
    history: 'History', noHistory: 'Nothing yet – solve your first task!', adminTitle: 'For teachers & authors: task database', adminLead: 'Overview of all tasks including inspiration source and licence. Add new tasks in js/content.js.', exportDb: 'Export database (JSON)', taskType: 'Type', source: 'Source', license: 'Licence',
    syncNote: 'The architecture is ready for future sign-in and sync (swappable storage adapter).', dataTitle: 'Data', dataLead: 'Progress is stored only on this device.', resetProgress: 'Reset progress', resetConfirm: 'Really delete stars, points and badges? Your name, grade and settings stay.', cancel: 'Cancel', yesReset: 'Yes, delete', resetDone: 'Progress was reset.'
  }
};
function t(key, vars) {
  let s = (I18N[LANG] && I18N[LANG][key]) ?? I18N.sk[key] ?? key;
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.replaceAll('{' + k + '}', v);
  return s;
}
