name = "logiq-api"
main = "worker.js"
compatibility_date = "2024-11-01"

[vars]
ALLOWED_ORIGINS = "https://zajo-sk.github.io,logiq://app"

# Po `wrangler kv namespace create LOGIQ_DB` doplň vygenerované id:
[[kv_namespaces]]
binding = "DB"
id = "6f61d62041884a2287a76db49c781cfe"
