name = "logiq-api"
main = "worker.js"
compatibility_date = "2024-11-01"

[vars]
ALLOWED_ORIGINS = "https://zajo-sk.github.io,logiq://app"

# Po `wrangler kv namespace create LOGIQ_DB` doplň vygenerované id:
[[kv_namespaces]]
binding = "DB"
id = "6f61d62041884a2287a76db49c781cfe"

# Silne konzistentná databáza (učitelia, triedy, žiaci, zadania). Schéma: schema.sql
[[d1_databases]]
binding = "SQL"
database_name = "logiq"
database_id = "b96c1008-7b6b-41e0-960e-38f8e15ad85e"
